-- language: sql
CREATE DATABASE ChordNoteMusic;

USE ChordNoteMusic;

-- Creazione della tabella DO
CREATE TABLE NoteDO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);

-- Inserimento dei dati per gli accordi di Do
INSERT INTO NoteDO (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('DO', 'Do Maggiore', 'Do-Mi-Sol', 'C', 'CMaj', 'C-E-G'),
('DO', 'Do Minore', 'Do-Mi♭-Sol', 'C', 'Cm', 'C-E♭-G'),
('DO', 'Do Settima', 'Do-Mi-Sol-Si♭', 'C', 'C7', 'C-E-G-B♭'),
('DO', 'Do Maggiore 7', 'Do-Mi-Sol-Si', 'C', 'CMaj7', 'C-E-G-B'),
('DO', 'Do Minore 7', 'Do-Mi♭-Sol-Si♭', 'C', 'Cm7', 'C-E♭-G-B♭'),
('DO', 'Do Settima Minore', 'Do-Mi♭-Sol-Si♭', 'C', 'Cm7', 'C-E♭-G-B♭'),
('DO', 'Do Maggiore 6', 'Do-Mi-Sol-La', 'C', 'C6', 'C-E-G-A'),
('DO', 'Do Minore 6', 'Do-Mi♭-Sol-La', 'C', 'Cm6', 'C-E♭-G-A'),
('DO', 'Do Settima 9', 'Do-Mi-Sol-Si♭-Re', 'C', 'C9', 'C-E-G-B♭-D'),
('DO', 'Do Maggiore 9', 'Do-Mi-Sol-Si-Re', 'C', 'CMaj9', 'C-E-G-B-D'),
('DO', 'Do Minore 9', 'Do-Mi♭-Sol-Si♭-Re', 'C', 'Cm9', 'C-E♭-G-B♭-D'),
('DO', 'Do Settima Maggiore 7', 'Do-Mi-Sol-Si♯', 'C', 'CMaj7♯5', 'C-E-G-B♯'),
('DO', 'Do Diminuito', 'Do-Mi♭-Sol♭', 'C', 'Cdim', 'C-E♭-G♭'),
('DO', 'Do Aumentato', 'Do-Mi-Sol♯', 'C', 'Caug', 'C-E-G♯'),
('DO', 'Do Sesta', 'Do-Mi-Sol-La', 'C', 'C6', 'C-E-G-A'),
('DO', 'Do Nona', 'Do-Mi-Sol-Si-Re', 'C', 'C9', 'C-E-G-B♭-D'),
('DO', 'Do Settima Maggiore', 'Do-Mi-Sol-Si', 'C', 'CMaj7', 'C-E-G-B'),
('DO', 'Do Settima Maggiore 9', 'Do-Mi-Sol-Si-Re', 'C', 'CMaj9', 'C-E-G-B-D'),
('DO', 'Do Settima 11', 'Do-Mi-Sol-Si♭-Re-Fa', 'C', 'C11', 'C-E-G-B♭-D-F'),
('DO', 'Do Settima 13', 'Do-Mi-Sol-Si♭-Re-Fa-La', 'C', 'C13', 'C-E-G-B♭-D-F-A'),
('DO', 'Do Settima 9 Add11', 'Do-Mi-Sol-Si♭-Re-Fa', 'C', 'C9add11', 'C-E-G-B♭-D-F'),
('DO', 'Do Sesta 9', 'Do-Mi-Sol-La-Re', 'C', 'C6/9', 'C-E-G-A-D'),
('DO', 'Do Sesta 11', 'Do-Mi-Sol-La-Re-Fa', 'C', 'C6/11', 'C-E-G-A-D-F'),
('DO', 'Do Settima Maggiore 11', 'Do-Mi-Sol-Si-Fa', 'C', 'CMaj7#11', 'C-E-G-B-F#'),
('DO', 'Do Minore 7 Add11', 'Do-Mi♭-Sol-B♭', 'C', 'Cm7add11', 'C-E♭-G-B♭-F'),
('DO', 'Do Maggiore 7#11', 'Do-Mi-Sol-Si-F♯', 'C', 'CMaj7#11', 'C-E-G-B-F#'),
('DO', 'Do Minore/Maggiore 7', 'Do-Mi♭-Sol-Si-B', 'C', 'Cm/Maj7', 'C-E♭-G-B'),
('DO', 'Do Settima 9#11', 'Do-Mi-Sol-Si♭-Re-F♯', 'C', 'C9#11', 'C-E-G-B♭-D-F#'),
('DO', 'Do Settima Minore 9', 'Do-Mi♭-Sol-Si♭-Re', 'C', 'Cm9', 'C-E♭-G-B♭-D'),
('DO', 'Do Settima Maggiore 13', 'Do-Mi-Sol-Si-Re-F♯-La', 'C', 'CMaj13', 'C-E-G-B-D-F#-A'),
('DO', 'Do Minore 11', 'Do-Mi♭-Sol-Si♭-Re-Fa', 'C', 'Cm11', 'C-E♭-G-B♭-D-F'),
('DO', 'Do Settima add11', 'Do-Mi-Sol-Si-Fa', 'C', 'C7add11', 'C-E-G-B-F');

-- Creazione della tabella DOb
CREATE TABLE NoteDOb (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);

-- Inserimento dei dati per gli accordi di DOb nella tabella DOb
INSERT INTO NoteDOb (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('DOb', 'DOb Maggiore', 'DOb-Fa♭-La♭', 'C#', 'C#Maj', 'C#-E#-G#'),
('DOb', 'DOb Minore', 'DOb-F♭-La♭♭', 'C#', 'C#m', 'C#-E-G#'),
('DOb', 'DOb Settima', 'DOb-F♭-La♭♭-Si♭', 'C#', 'C#7', 'C#-E-G#-B'),
('DOb', 'DOb Maggiore 7', 'DOb-F♭-La♭♭-Si', 'C#', 'C#Maj7', 'C#-E#-G#-B#'),
('DOb', 'DOb Minore 7', 'DOb-F♭-La♭♭-Si♭', 'C#', 'C#m7', 'C#-E-G#-B'),
('DOb', 'DOb Settima Minore', 'DOb-F♭-La♭♭-Si♭', 'C#', 'C#m7', 'C#-E-G#-B'),
('DOb', 'DOb Maggiore 6', 'DOb-F♭-La♭♭-Si', 'C#', 'C#6', 'C#-E#-G#-A#'),
('DOb', 'DOb Minore 6', 'DOb-F♭-La♭♭-Si', 'C#', 'C#m6', 'C#-E-G#-A'),
('DOb', 'DOb Settima 9', 'DOb-F♭-La♭♭-Si♭-Re', 'C#', 'C#9', 'C#-E-G#-B-D#'),
('DOb', 'DOb Maggiore 9', 'DOb-F♭-La♭♭-Si-Re', 'C#', 'C#Maj9', 'C#-E#-G#-B#-D#'),
('DOb', 'DOb Minore 9', 'DOb-F♭-La♭♭-Si♭-Re', 'C#', 'C#m9', 'C#-E-G#-B-D#'),
('DOb', 'DOb Settima Maggiore 7', 'DOb-F♭-La♭♭-Si♯', 'C#', 'C#Maj7♯5', 'C#-E#-G#-B#'),
('DOb', 'DOb Diminuito', 'DOb-F♭-La♭♭♭', 'C#', 'C#dim', 'C#-E-G'),
('DOb', 'DOb Aumentato', 'DOb-F♭-La♭♯', 'C#', 'C#aug', 'C#-E#-G##'),
('DOb', 'DOb Sesta', 'DOb-F♭-La♭♭-Mi', 'C#', 'C#6', 'C#-E#-G#-A#'),
('DOb', 'DOb Nona', 'DOb-F♭-La♭♭-Si♭-Re', 'C#', 'C#9', 'C#-E-G#-B-D#'),
('DOb', 'DOb Settima Maggiore', 'DOb-F♭-La♭♭-Si', 'C#', 'C#Maj7', 'C#-E#-G#-B#'),
('DOb', 'DOb Settima Maggiore 9', 'DOb-F♭-La♭♭-Si-Re', 'C#', 'C#Maj9', 'C#-E#-G#-B#-D#'),
('DOb', 'DOb Settima 11', 'DOb-F♭-La♭♭-Si♭-Re-Fa', 'C#', 'C#11', 'C#-E-G#-B-D-F'),
('DOb', 'DOb Settima 13', 'DOb-F♭-La♭♭-Si♭-Re-Fa-La', 'C#', 'C#13', 'C#-E-G#-B-D-F-A'),
('DOb', 'DOb Settima 9 Add11', 'DOb-F♭-La♭♭-Si♭-Re-Fa', 'C#', 'C#9add11', 'C#-E-G#-B-D-F'),
('DOb', 'DOb Sesta 9', 'DOb-F♭-La♭♭-Mi-La-Re', 'C#', 'C#6/9', 'C#-E#-G#-A#-D#'),
('DOb', 'DOb Sesta 11', 'DOb-F♭-La♭♭-Mi-La-Re-Fa', 'C#', 'C#6/11', 'C#-E#-G#-A#-D#-F'),
('DOb', 'DOb Settima Maggiore 11', 'DOb-F♭-La♭♭-Si-Fa', 'C#', 'C#Maj7#11', 'C#-E#-G#-B#-F#'),
('DOb', 'DOb Minore 7 Add11', 'DOb-F♭-La♭♭♭-Si♭', 'C#', 'C#m7add11', 'C#-E-G-B-D-F'),
('DOb', 'DOb Maggiore 7#11', 'DOb-F♭-La♭♭-Si-F♯', 'C#', 'C#Maj7#11', 'C#-E#-G#-B#-F#'),
('DOb', 'DOb Minore/Maggiore 7', 'DOb-F♭-La♭♭-Si-B', 'C#', 'C#m/Maj7', 'C#-E-G#-B'),
('DOb', 'DOb Settima 9#11', 'DOb-F♭-La♭♭-Si♭-Re-F♯', 'C#', 'C#9#11', 'C#-E-G#-B-D-F#'),
('DOb', 'DOb Settima Minore 9', 'DOb-F♭-La♭♭-Si♭-Re', 'C#', 'C#m9', 'C#-E-G#-B-D'),
('DOb', 'DOb Settima Maggiore 13', 'DOb-F♭-La♭♭-Si-Re-F♯-La', 'C#', 'C#Maj13', 'C#-E#-G#-B#-D#-F#-A'),
('DOb', 'DOb Minore 11', 'DOb-F♭-La♭♭-Si♭-Re-Fa', 'C#', 'C#m11', 'C#-E-G-B-D-F'),
('DOb', 'DOb Settima add11', 'DOb-F♭-La♭♭-Si-Fa', 'C#', 'C#7add11', 'C#-E-G#-B-F');

-- Creazione della tabella DO#
CREATE TABLE NoteDOdiesis (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);

-- Inserimento dei dati per gli accordi di DO# nella tabella DO#
INSERT INTO NoteDO# (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('DO#', 'DO# Maggiore', 'DO#-Fa-La', 'C#', 'C#Maj', 'C#-E#-G#'),
('DO#', 'DO# Minore', 'DO#-Fa♯-La', 'C#', 'C#m', 'C#-E-G#'),
('DO#', 'DO# Settima', 'DO#-Fa-La-Si', 'C#', 'C#7', 'C#-E-G#-B'),
('DO#', 'DO# Maggiore 7', 'DO#-Fa-La-Si♯', 'C#', 'C#Maj7', 'C#-E#-G#-B#'),
('DO#', 'DO# Minore 7', 'DO#-Fa♯-La-Si', 'C#', 'C#m7', 'C#-E-G#-B'),
('DO#', 'DO# Settima Minore', 'DO#-Fa♯-La-Si', 'C#', 'C#m7', 'C#-E-G#-B'),
('DO#', 'DO# Maggiore 6', 'DO#-Fa-La♯', 'C#', 'C#6', 'C#-E#-G#-A#'),
('DO#', 'DO# Minore 6', 'DO#-Fa♯-La♯', 'C#', 'C#m6', 'C#-E-G#-A'),
('DO#', 'DO# Settima 9', 'DO#-Fa-La-Si-Re', 'C#', 'C#9', 'C#-E-G#-B-D#'),
('DO#', 'DO# Maggiore 9', 'DO#-Fa-La-Si♯-Re', 'C#', 'C#Maj9', 'C#-E#-G#-B#-D#'),
('DO#', 'DO# Minore 9', 'DO#-Fa♯-La-Si-Re', 'C#', 'C#m9', 'C#-E-G#-B-D#'),
('DO#', 'DO# Settima Maggiore 7', 'DO#-Fa-La-Si♯♯', 'C#', 'C#Maj7♯5', 'C#-E#-G#-B#'),
('DO#', 'DO# Diminuito', 'DO#-Fa-La♭', 'C#', 'C#dim', 'C#-E-G'),
('DO#', 'DO# Aumentato', 'DO#-Fa♯-La♯♯', 'C#', 'C#aug', 'C#-E#-G##'),
('DO#', 'DO# Sesta', 'DO#-Fa-La♯-Mi', 'C#', 'C#6', 'C#-E#-G#-A#'),
('DO#', 'DO# Nona', 'DO#-Fa-La-Si-Re', 'C#', 'C#9', 'C#-E-G#-B-D#'),
('DO#', 'DO# Settima Maggiore', 'DO#-Fa-La-Si', 'C#', 'C#Maj7', 'C#-E#-G#-B#'),
('DO#', 'DO# Settima Maggiore 9', 'DO#-Fa-La-Si♯-Re', 'C#', 'C#Maj9', 'C#-E#-G#-B#-D#'),
('DO#', 'DO# Settima 11', 'DO#-Fa-La-Si♯-Re-Fa♯', 'C#', 'C#11', 'C#-E-G#-B-D-F#'),
('DO#', 'DO# Settima 13', 'DO#-Fa-La-Si♯-Re-Fa♯-La', 'C#', 'C#13', 'C#-E-G#-B-D-F#-A'),
('DO#', 'DO# Settima 9 Add11', 'DO#-Fa-La-Si♯-Re-Fa♯', 'C#', 'C#9add11', 'C#-E-G#-B-D-F#'),
('DO#', 'DO# Sesta 9', 'DO#-Fa-La♯-Mi-La-Re', 'C#', 'C#6/9', 'C#-E#-G#-A#-D#'),
('DO#', 'DO# Sesta 11', 'DO#-Fa-La♯-Mi-La-Re-Fa♯', 'C#', 'C#6/11', 'C#-E#-G#-A#-D#-F#'),
('DO#', 'DO# Settima Maggiore 11', 'DO#-Fa-La-Si-Fa♯', 'C#', 'C#Maj7#11', 'C#-E#-G#-B#-F#'),
('DO#', 'DO# Minore 7 Add11', 'DO#-Fa♯-La♭-Si', 'C#', 'C#m7add11', 'C#-E-G-B-D-F#'),
('DO#', 'DO# Maggiore 7#11', 'DO#-Fa-La-Si-F♯', 'C#', 'C#Maj7#11', 'C#-E#-G#-B#-F#'),
('DO#', 'DO# Minore/Maggiore 7', 'DO#-Fa♯-La♭-Si♯', 'C#', 'C#m/Maj7', 'C#-E-G#-B#'),
('DO#', 'DO# Settima 9#11', 'DO#-Fa-La-Si♯-Re-F♯', 'C#', 'C#9#11', 'C#-E-G#-B-D-F#'),
('DO#', 'DO# Settima Minore 9', 'DO#-Fa♯-La♭-Si♯-Re', 'C#', 'C#m9', 'C#-E-G#-B#-D#'),
('DO#', 'DO# Settima Maggiore 13', 'DO#-Fa-La-Si-Re-F♯-La', 'C#', 'C#Maj13', 'C#-E#-G#-B#-D#-F#-A'),
('DO#', 'DO# Minore 11', 'DO#-Fa♯-La♭-Si♯-Re-Fa♯', 'C#', 'C#m11', 'C#-E-G-B-D-F#'),
('DO#', 'DO# Settima add11', 'DO#-Fa-La-Si-Fa♯', 'C#', 'C#7add11', 'C#-E-G#-B-F#');

-- Creazione della tabella RE
CREATE TABLE NoteRE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);

-- Inserimento dei dati per gli accordi di Re nella tabella RE
INSERT INTO NoteRE (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('RE', 'Re Maggiore', 'Re-Fa♯-La', 'D', 'DMaj', 'D-F#-A'),
('RE', 'Re Minore', 'Re-Fa-La', 'D', 'Dm', 'D-F-A'),
('RE', 'Re Settima', 'Re-Fa-La-Si', 'D', 'D7', 'D-F#-A-C'),
('RE', 'Re Maggiore 7', 'Re-Fa♯-La-Si', 'D', 'DMaj7', 'D-F#-A-C#'),
('RE', 'Re Minore 7', 'Re-Fa-La-Si♭', 'D', 'Dm7', 'D-F-A-C'),
('RE', 'Re Settima Minore', 'Re-Fa-La-Si♭', 'D', 'Dm7', 'D-F-A-C'),
('RE', 'Re Maggiore 6', 'Re-Fa♯-La♯', 'D', 'D6', 'D-F#-A-B'),
('RE', 'Re Minore 6', 'Re-Fa-La♯', 'D', 'Dm6', 'D-F-A-B'),
('RE', 'Re Settima 9', 'Re-Fa-La-Si-Re', 'D', 'D9', 'D-F#-A-C-E'),
('RE', 'Re Maggiore 9', 'Re-Fa♯-La-Si-Re', 'D', 'DMaj9', 'D-F#-A-C#-E'),
('RE', 'Re Minore 9', 'Re-Fa-La-Si♭-Re', 'D', 'Dm9', 'D-F-A-C-E'),
('RE', 'Re Settima Maggiore 7', 'Re-Fa♯-La-Si♯', 'D', 'DMaj7♯5', 'D-F#-A-C#'),
('RE', 'Re Diminuito', 'Re-Fa-La♭', 'D', 'Ddim', 'D-F-A♭'),
('RE', 'Re Aumentato', 'Re-Fa♯-La♯♯', 'D', 'Daug', 'D-F#-A##'),
('RE', 'Re Sesta', 'Re-Fa♯-La-Si♯', 'D', 'D6', 'D-F#-A-B'),
('RE', 'Re Nona', 'Re-Fa-La-Si-Re', 'D', 'D9', 'D-F#-A-C-E'),
('RE', 'Re Settima Maggiore', 'Re-Fa♯-La-Si', 'D', 'DMaj7', 'D-F#-A-C#'),
('RE', 'Re Settima Maggiore 9', 'Re-Fa♯-La-Si-Re', 'D', 'DMaj9', 'D-F#-A-C#-E'),
('RE', 'Re Settima 11', 'Re-Fa-La-Si♭-Re-Fa', 'D', 'D11', 'D-F-A-C-E-G'),
('RE', 'Re Settima 13', 'Re-Fa-La-Si♭-Re-Fa-La', 'D', 'D13', 'D-F-A-C-E-G-B'),
('RE', 'Re Settima 9 Add11', 'Re-Fa-La-Si♭-Re-Fa', 'D', 'D9add11', 'D-F-A-C-E-G'),
('RE', 'Re Sesta 9', 'Re-Fa♯-La-Si♯-Re♯', 'D', 'D6/9', 'D-F#-A-B-E'),
('RE', 'Re Sesta 11', 'Re-Fa♯-La-Si♯-Re♯-Fa', 'D', 'D6/11', 'D-F#-A-B-E-G'),
('RE', 'Re Settima Maggiore 11', 'Re-Fa♯-La-Si-Re-Fa', 'D', 'DMaj7#11', 'D-F#-A-C#-E-G#'),
('RE', 'Re Minore 7 Add11', 'Re-Fa-La♭-Si', 'D', 'Dm7add11', 'D-F-A-C-E-G'),
('RE', 'Re Maggiore 7#11', 'Re-Fa♯-La-Si-Re-F♯', 'D', 'DMaj7#11', 'D-F#-A-C#-E-G#'),
('RE', 'Re Minore/Maggiore 7', 'Re-Fa-La-Si-Re♯', 'D', 'Dm/Maj7', 'D-F-A-C#-E'),
('RE', 'Re Settima 9#11', 'Re-Fa-La-Si♭-Re-F♯', 'D', 'D9#11', 'D-F-A-C-E-G#'),
('RE', 'Re Settima Minore 9', 'Re-Fa-La-Si♭-Re♭', 'D', 'Dm9', 'D-F-A-C-E'),
('RE', 'Re Settima Maggiore 13', 'Re-Fa♯-La-Si-Re-Fa-La', 'D', 'DMaj13', 'D-F#-A-C#-E-G#-B'),
('RE', 'Re Minore 11', 'Re-Fa-La-Si♭-Re-Fa♯', 'D', 'Dm11', 'D-F-A-C-E-G#'),
('RE', 'Re Settima add11', 'Re-Fa-La-Si-Re-Fa', 'D', 'D7add11', 'D-F-A-C-E-G');

-- Creazione della tabella REb
CREATE TABLE NoteREb (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);

-- Inserimento dei dati per gli accordi di Re♭ nella tabella REb
INSERT INTO NoteREb (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('RE♭', 'Re♭ Maggiore', 'Re♭-Fa-La♭', 'D♭', 'D♭Maj', 'D♭-F-A♭'),
('RE♭', 'Re♭ Minore', 'Re♭-Fa♭-La♭', 'D♭', 'D♭m', 'D♭-F♭-A♭'),
('RE♭', 'Re♭ Settima', 'Re♭-Fa-La♭-Si♭', 'D♭', 'D♭7', 'D♭-F-A♭-C♭'),
('RE♭', 'Re♭ Maggiore 7', 'Re♭-Fa-La♭-Si', 'D♭', 'D♭Maj7', 'D♭-F-A♭-C'),
('RE♭', 'Re♭ Minore 7', 'Re♭-Fa♭-La♭-Si♭♭', 'D♭', 'D♭m7', 'D♭-F♭-A♭-C♭'),
('RE♭', 'Re♭ Settima Minore', 'Re♭-Fa♭-La♭-Si♭♭', 'D♭', 'D♭m7', 'D♭-F♭-A♭-C♭'),
('RE♭', 'Re♭ Maggiore 6', 'Re♭-Fa-La♭-Mi♭', 'D♭', 'D♭6', 'D♭-F-A♭-B♭'),
('RE♭', 'Re♭ Minore 6', 'Re♭-Fa♭-La♭-Mi♭', 'D♭', 'D♭m6', 'D♭-F♭-A♭-B♭'),
('RE♭', 'Re♭ Settima 9', 'Re♭-Fa-La♭-Si♭-Re♭', 'D♭', 'D♭9', 'D♭-F-A♭-C♭-E♭'),
('RE♭', 'Re♭ Maggiore 9', 'Re♭-Fa-La♭-Si-♭Re♭', 'D♭', 'D♭Maj9', 'D♭-F-A♭-C-E♭'),
('RE♭', 'Re♭ Minore 9', 'Re♭-Fa♭-La♭-Si♭-Re♭', 'D♭', 'D♭m9', 'D♭-F♭-A♭-C♭-E♭'),
('RE♭', 'Re♭ Settima Maggiore 7', 'Re♭-Fa-La♭-Si♯', 'D♭', 'D♭Maj7♯5', 'D♭-F-A♭-C♭-E'),
('RE♭', 'Re♭ Diminuito', 'Re♭-Fa♭-La♭♭', 'D♭', 'D♭dim', 'D♭-F♭-A♭♭'),
('RE♭', 'Re♭ Aumentato', 'Re♭-Fa-La', 'D♭', 'D♭aug', 'D♭-F-A'),
('RE♭', 'Re♭ Sesta', 'Re♭-Fa-La♭-Mi♭', 'D♭', 'D♭6', 'D♭-F-A♭-B♭'),
('RE♭', 'Re♭ Nona', 'Re♭-Fa-La♭-Si♭-Re♭', 'D♭', 'D♭9', 'D♭-F-A♭-C♭-E♭'),
('RE♭', 'Re♭ Settima Maggiore', 'Re♭-Fa-La♭-Si♭', 'D♭', 'D♭Maj7', 'D♭-F-A♭-C♭'),
('RE♭', 'Re♭ Settima Maggiore 9', 'Re♭-Fa-La♭-Si♯-Re♭', 'D♭', 'D♭Maj9', 'D♭-F-A♭-C♭-E'),
('RE♭', 'Re♭ Settima 11', 'Re♭-Fa-La♭-Si-♭Re♭-♭Fa', 'D♭', 'D♭11', 'D♭-F-A♭-C♭-E♭-G'),
('RE♭', 'Re♭ Settima 13', 'Re♭-Fa-La♭-Si-♭Re♭-♭Fa-La', 'D♭', 'D♭13', 'D♭-F-A♭-C♭-E♭-G-B'),
('RE♭', 'Re♭ Settima 9 Add11', 'Re♭-Fa-La♭-Si-♭Re♭-♭Fa', 'D♭', 'D♭9add11', 'D♭-F-A♭-C♭-E♭-G'),
('RE♭', 'Re♭ Sesta 9', 'Re♭-Fa-La♭-Mi♭-La-Re♭', 'D♭', 'D♭6/9', 'D♭-F-A♭-B♭-E♭'),
('RE♭', 'Re♭ Sesta 11', 'Re♭-Fa-La♭-Mi♭-La-Re♭-♭Fa', 'D♭', 'D♭6/11', 'D♭-F-A♭-B♭-E♭-G'),
('RE♭', 'Re♭ Settima Maggiore 11', 'Re♭-Fa-La♭-Si♭-F♭', 'D♭', 'D♭Maj7#11', 'D♭-F-A♭-C♭-E♭-G#'),
('RE♭', 'Re♭ Minore 7 Add11', 'Re♭-Fa♭-La♭-Si♭♯', 'D♭', 'D♭m7add11', 'D♭-F♭-A♭-C♭-D'),
('RE♭', 'Re♭ Maggiore 7#11', 'Re♭-Fa-La♭-Si♭♯', 'D♭', 'D♭Maj7#11', 'D♭-F-A♭-C♭-D'),
('RE♭', 'Re♭ Minore/Maggiore 7', 'Re♭-Fa♭-La♭-Si', 'D♭', 'D♭m/Maj7', 'D♭-F♭-A♭-C'),
('RE♭', 'Re♭ Settima 9#11', 'Re♭-Fa♭-La♭-Si♭-♭Re♭-♭Fa', 'D♭', 'D♭9#11', 'D♭-F♭-A♭-C♭-D♭-G'),
('RE♭', 'Re♭ Settima Minore 9', 'Re♭-Fa♭-La♭-Si♭-♭Re♭', 'D♭', 'D♭m9', 'D♭-F♭-A♭-C♭-D♭-G'),
('RE♭', 'Re♭ Settima Maggiore 13', 'Re♭-Fa-La♭-Si-♭Re♭-♭Fa-La', 'D♭', 'D♭Maj13', 'D♭-F-A♭-C♭-E♭-G#-B'),
('RE♭', 'Re♭ Minore 11', 'Re♭-Fa♭-La♭-Si♭-♭Re♭-♭Fa', 'D♭', 'D♭m11', 'D♭-F♭-A♭-C♭-D♭-G#-B'),
('RE♭', 'Re♭ Settima add11', 'Re♭-Fa-La♭-Si♭-♭Re♭-♭Fa', 'D♭', 'D♭7add11', 'D♭-F-A♭-C♭-D♭-G#');

-- Creazione della tabella RE#
CREATE TABLE NoteREdiesis (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);

-- Inserimento dei dati per gli accordi di Re# nella tabella RE#
INSERT INTO NoteRE# (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('RE#', 'Re# Maggiore', 'Re#-Sol-La#', 'D#', 'D#Maj', 'D#-G-A#'),
('RE#', 'Re# Minore', 'Re#-Sol♯-La#', 'D#', 'D#m', 'D#-G#-A#'),
('RE#', 'Re# Settima', 'Re#-Sol-La#-Si#', 'D#', 'D#7', 'D#-G-A#-D'),
('RE#', 'Re# Maggiore 7', 'Re#-Sol-La#-Si♯', 'D#', 'D#Maj7', 'D#-G-A#-D#'),
('RE#', 'Re# Minore 7', 'Re#-Sol♯-La#-Si', 'D#', 'D#m7', 'D#-G#-A#-D'),
('RE#', 'Re# Settima Minore', 'Re#-Sol♯-La#-Si', 'D#', 'D#m7', 'D#-G#-A#-D'),
('RE#', 'Re# Maggiore 6', 'Re#-Sol-La#-Mi#', 'D#', 'D#6', 'D#-G-A#-E#'),
('RE#', 'Re# Minore 6', 'Re#-Sol♯-La#-Mi#', 'D#', 'D#m6', 'D#-G#-A#-E#'),
('RE#', 'Re# Settima 9', 'Re#-Sol-La#-Si#-Re#', 'D#', 'D#9', 'D#-G-A#-D#-F#'),
('RE#', 'Re# Maggiore 9', 'Re#-Sol-La#-Si♯-Re#', 'D#', 'D#Maj9', 'D#-G-A#-D#-F#'),
('RE#', 'Re# Minore 9', 'Re#-Sol♯-La#-Si-♯Re#', 'D#', 'D#m9', 'D#-G#-A#-D#-F#'),
('RE#', 'Re# Settima Maggiore 7', 'Re#-Sol-La#-Si#♯', 'D#', 'D#Maj7♯5', 'D#-G-A#-D#-F#'),
('RE#', 'Re# Diminuito', 'Re#-Sol♯-La', 'D#', 'D#dim', 'D#-G#-A'),
('RE#', 'Re# Aumentato', 'Re#-Sol-La##', 'D#', 'D#aug', 'D#-G-A##'),
('RE#', 'Re# Sesta', 'Re#-Sol-La#-Mi#', 'D#', 'D#6', 'D#-G-A#-E#'),
('RE#', 'Re# Nona', 'Re#-Sol-La#-Si#-Re#', 'D#', 'D#9', 'D#-G-A#-D#-F#'),
('RE#', 'Re# Settima Maggiore', 'Re#-Sol-La#-Si#', 'D#', 'D#Maj7', 'D#-G-A#-D#-F#'),
('RE#', 'Re# Settima Maggiore 9', 'Re#-Sol-La#-Si♯-Re#', 'D#', 'D#Maj9', 'D#-G-A#-D#-F#'),
('RE#', 'Re# Settima 11', 'Re#-Sol-La#-Si-♭Re#-♭Fa', 'D#', 'D#11', 'D#-G-A#-D#-F#-A#'),
('RE#', 'Re# Settima 13', 'Re#-Sol-La#-Si-♭Re#-♭Fa-La', 'D#', 'D#13', 'D#-G-A#-D#-F#-A#-C#'),
('RE#', 'Re# Settima 9 Add11', 'Re#-Sol-La#-Si-♭Re#-♭Fa', 'D#', 'D#9add11', 'D#-G-A#-D#-F#-A#'),
('RE#', 'Re# Sesta 9', 'Re#-Sol-La#-Mi#-La-Re#', 'D#', 'D#6/9', 'D#-G-A#-E#-F#'),
('RE#', 'Re# Sesta 11', 'Re#-Sol-La#-Mi#-La-Re#-♭Fa', 'D#', 'D#6/11', 'D#-G-A#-E#-F#-A#'),
('RE#', 'Re# Settima Maggiore 11', 'Re#-Sol-La#-Si♯-F♯', 'D#', 'D#Maj7#11', 'D#-G-A#-D#-F#-C##'),
('RE#', 'Re# Minore 7 Add11', 'Re#-Sol♯-La-♭Si#', 'D#', 'D#m7add11', 'D#-G#-A-D#-F#-A#'),
('RE#', 'Re# Maggiore 7#11', 'Re#-Sol-La#-Si-♭Re#-♭Fa', 'D#', 'D#Maj7#11', 'D#-G-A#-D#-F#-A#'),
('RE#', 'Re# Minore/Maggiore 7', 'Re#-Sol♯-La-♭Si', 'D#', 'D#m/Maj7', 'D#-G#-A-D#-F#'),
('RE#', 'Re# Settima 9#11', 'Re#-Sol-La#-Si-♭Re#-♭Fa♯', 'D#', 'D#9#11', 'D#-G-A#-D#-F#-A#-C##'),
('RE#', 'Re# Settima Minore 9', 'Re#-Sol♯-La-♭Si-♭Re#', 'D#', 'D#m9', 'D#-G#-A-D#-F#-A#'),
('RE#', 'Re# Settima Maggiore 13', 'Re#-Sol-La#-Si-♭Re#-♭Fa-La', 'D#', 'D#Maj13', 'D#-G-A#-D#-F#-A#-C##'),
('RE#', 'Re# Minore 11', 'Re#-Sol♯-La-♭Si-♭Re#-♭Fa', 'D#', 'D#m11', 'D#-G#-A-D#-F#-A#-C##'),
('RE#', 'Re# Settima add11', 'Re#-Sol-La#-Si-♭Re#-♭Fa', 'D#', 'D#7add11', 'D#-G-A#-D#-F#-A#');

-- Creazione della tabella MI
CREATE TABLE NoteMI (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);

-- Inserimento dei dati per gli accordi di Mi nella tabella MI
INSERT INTO NoteMI (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('MI', 'Mi Maggiore', 'Mi-Sol♯-Si', 'E', 'EMaj', 'E-G♯-B'),
('MI', 'Mi Minore', 'Mi-Sol-Si', 'E', 'Em', 'E-G-B'),
('MI', 'Mi Settima', 'Mi-Sol♯-Si-Re', 'E', 'E7', 'E-G♯-B-D'),
('MI', 'Mi Maggiore 7', 'Mi-Sol♯-Si-Re♯', 'E', 'EMaj7', 'E-G♯-B-D♯'),
('MI', 'Mi Minore 7', 'Mi-Sol-Si-Re', 'E', 'Em7', 'E-G-B-D'),
('MI', 'Mi Settima Minore', 'Mi-Sol-Si-Re♭', 'E', 'Em7', 'E-G-B-D'),
('MI', 'Mi Maggiore 6', 'Mi-Sol♯-Si-La♯', 'E', 'E6', 'E-G♯-B-C♯'),
('MI', 'Mi Minore 6', 'Mi-Sol-Si-La', 'E', 'Em6', 'E-G-B-C♯'),
('MI', 'Mi Settima 9', 'Mi-Sol♯-Si-Re-Fa♯', 'E', 'E9', 'E-G♯-B-D-F♯'),
('MI', 'Mi Maggiore 9', 'Mi-Sol♯-Si-Re♯-Fa♯', 'E', 'EMaj9', 'E-G♯-B-D♯-F♯'),
('MI', 'Mi Minore 9', 'Mi-Sol-Si-Re-Fa♯', 'E', 'Em9', 'E-G-B-D-F♯'),
('MI', 'Mi Settima Maggiore 7', 'Mi-Sol♯-Si-Re♯', 'E', 'EMaj7♯5', 'E-G♯-B-D♯'),
('MI', 'Mi Diminuito', 'Mi-Sol-Si♭', 'E', 'Edim', 'E-G-B♭'),
('MI', 'Mi Aumentato', 'Mi-Sol♯-Si♯', 'E', 'Eaug', 'E-G♯-B♯'),
('MI', 'Mi Sesta', 'Mi-Sol♯-Si-La♯', 'E', 'E6', 'E-G♯-B-C♯'),
('MI', 'Mi Nona', 'Mi-Sol♯-Si-Re-Fa♯', 'E', 'E9', 'E-G♯-B-D-F♯'),
('MI', 'Mi Settima Maggiore', 'Mi-Sol♯-Si-Re♯', 'E', 'EMaj7', 'E-G♯-B-D♯'),
('MI', 'Mi Settima Maggiore 9', 'Mi-Sol♯-Si-Re♯-Fa♯', 'E', 'EMaj9', 'E-G♯-B-D♯-F♯'),
('MI', 'Mi Settima 11', 'Mi-Sol♯-Si-Re-Fa♯-La', 'E', 'E11', 'E-G♯-B-D-F♯-A'),
('MI', 'Mi Settima 13', 'Mi-Sol♯-Si-Re-Fa♯-La-Do♯', 'E', 'E13', 'E-G♯-B-D-F♯-A-C♯'),
('MI', 'Mi Settima 9 Add11', 'Mi-Sol♯-Si-Re-Fa♯-La', 'E', 'E9add11', 'E-G♯-B-D-F♯-A'),
('MI', 'Mi Sesta 9', 'Mi-Sol♯-Si-La♯-Re♯', 'E', 'E6/9', 'E-G♯-B-C♯-D♯'),
('MI', 'Mi Sesta 11', 'Mi-Sol♯-Si-La♯-Re♯-Fa♯', 'E', 'E6/11', 'E-G♯-B-C♯-D♯-F♯'),
('MI', 'Mi Settima Maggiore 11', 'Mi-Sol♯-Si-Re♯-Fa', 'E', 'EMaj7#11', 'E-G♯-B-D♯-F'),
('MI', 'Mi Minore 7 Add11', 'Mi-Sol-Si-Re-Fa', 'E', 'Em7add11', 'E-G-B-D-F♯'),
('MI', 'Mi Maggiore 7#11', 'Mi-Sol♯-Si-Re-Fa♯', 'E', 'EMaj7#11', 'E-G♯-B-D♯-F♯'),
('MI', 'Mi Minore/Maggiore 7', 'Mi-Sol-Si-Re-Fa♯', 'E', 'Em/Maj7', 'E-G-B-D♯-F♯'),
('MI', 'Mi Settima 9#11', 'Mi-Sol♯-Si-Re-Fa♯-La♯', 'E', 'E9#11', 'E-G♯-B-D♯-F♯-A♯'),
('MI', 'Mi Settima Minore 9', 'Mi-Sol-Si-Re♭-Fa', 'E', 'Em9', 'E-G-B-D-F♯-A'),
('MI', 'Mi Settima Maggiore 13', 'Mi-Sol♯-Si-Re♯-Fa♯-La-Do♯', 'E', 'EMaj13', 'E-G♯-B-D♯-F♯-A-C♯'),
('MI', 'Mi Minore 11', 'Mi-Sol-Si-Re-Fa♯-La-Do', 'E', 'Em11', 'E-G-B-D-F♯-A-C♯'),
('MI', 'Mi Settima add11', 'Mi-Sol♯-Si-Re-Fa', 'E', 'E7add11', 'E-G♯-B-D♯-F♯');

-- Creazione della tabella MIb
CREATE TABLE NoteMIb (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);

-- Inserimento dei dati per gli accordi di Mi♭ nella tabella MIb
INSERT INTO NoteMIb (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('MI♭', 'Mi♭ Maggiore', 'Mi♭-Sol-Si♭', 'Eb', 'EbMaj', 'Eb-G-B♭'),
('MI♭', 'Mi♭ Minore', 'Mi♭-Sol♭-Si♭', 'Eb', 'Ebm', 'Eb-G♭-B♭'),
('MI♭', 'Mi♭ Settima', 'Mi♭-Sol-Si♭-Re♭', 'Eb', 'Eb7', 'Eb-G-B♭-Db'),
('MI♭', 'Mi♭ Maggiore 7', 'Mi♭-Sol-Si♭-Re', 'Eb', 'EbMaj7', 'Eb-G-B♭-D'),
('MI♭', 'Mi♭ Minore 7', 'Mi♭-Sol♭-Si♭-Re♭', 'Eb', 'Ebm7', 'Eb-G♭-B♭-Db'),
('MI♭', 'Mi♭ Settima Minore', 'Mi♭-Sol♭-Si♭-Re♭', 'Eb', 'Ebm7', 'Eb-G♭-B♭-Db'),
('MI♭', 'Mi♭ Maggiore 6', 'Mi♭-Sol-Si♭-La', 'Eb', 'Eb6', 'Eb-G-B♭-A'),
('MI♭', 'Mi♭ Minore 6', 'Mi♭-Sol♭-Si♭-La', 'Eb', 'Ebm6', 'Eb-G♭-B♭-A'),
('MI♭', 'Mi♭ Settima 9', 'Mi♭-Sol-Si♭-Re♭-Fa', 'Eb', 'Eb9', 'Eb-G-B♭-Db-F'),
('MI♭', 'Mi♭ Maggiore 9', 'Mi♭-Sol-Si♭-Re-Fa', 'Eb', 'EbMaj9', 'Eb-G-B♭-D-F'),
('MI♭', 'Mi♭ Minore 9', 'Mi♭-Sol♭-Si♭-Re-Fa', 'Eb', 'Ebm9', 'Eb-G♭-B♭-Db-F'),
('MI♭', 'Mi♭ Settima Maggiore 7', 'Mi♭-Sol-Si♭-Re-F', 'Eb', 'EbMaj7♯5', 'Eb-G-B♭-D-F#'),
('MI♭', 'Mi♭ Diminuito', 'Mi♭-Sol♭-Si♭♭', 'Eb', 'Ebdim', 'Eb-G♭-B♭♭'),
('MI♭', 'Mi♭ Aumentato', 'Mi♭-Sol-Si', 'Eb', 'Ebaug', 'Eb-G-B'),
('MI♭', 'Mi♭ Sesta', 'Mi♭-Sol-Si♭-La', 'Eb', 'Eb6', 'Eb-G-B♭-A'),
('MI♭', 'Mi♭ Nona', 'Mi♭-Sol-Si♭-Re♭-Fa', 'Eb', 'Eb9', 'Eb-G-B♭-Db-F'),
('MI♭', 'Mi♭ Settima Maggiore', 'Mi♭-Sol-Si♭-Re-F', 'Eb', 'EbMaj7', 'Eb-G-B♭-D-F'),
('MI♭', 'Mi♭ Settima Maggiore 9', 'Mi♭-Sol-Si♭-Re-F-Fa', 'Eb', 'EbMaj9', 'Eb-G-B♭-D-F-F#'),
('MI♭', 'Mi♭ Settima 11', 'Mi♭-Sol-Si♭-Re-F-Fa-La♭', 'Eb', 'Eb11', 'Eb-G-B♭-Db-F-Ab'),
('MI♭', 'Mi♭ Settima 13', 'Mi♭-Sol-Si♭-Re-F-Fa-La♭-Do', 'Eb', 'Eb13', 'Eb-G-B♭-Db-F-Ab-C'),
('MI♭', 'Mi♭ Settima 9 Add11', 'Mi♭-Sol-Si♭-Re-F-Fa', 'Eb', 'Eb9add11', 'Eb-G-B♭-Db-F-Ab'),
('MI♭', 'Mi♭ Sesta 9', 'Mi♭-Sol-Si♭-La-Re♭', 'Eb', 'Eb6/9', 'Eb-G-B♭-A-Db'),
('MI♭', 'Mi♭ Sesta 11', 'Mi♭-Sol-Si♭-La-Re♭-Fa', 'Eb', 'Eb6/11', 'Eb-G-B♭-A-Db-F'),
('MI♭', 'Mi♭ Settima Maggiore 11', 'Mi♭-Sol-Si♭-Re-Fa♭', 'Eb', 'EbMaj7#11', 'Eb-G-B♭-D-Fb'),
('MI♭', 'Mi♭ Minore 7 Add11', 'Mi♭-Sol♭-Si♭-Re-F', 'Eb', 'Ebm7add11', 'Eb-G♭-B♭-Db-F'),
('MI♭', 'Mi♭ Maggiore 7#11', 'Mi♭-Sol-Si♭-Re-Fa', 'Eb', 'EbMaj7#11', 'Eb-G-B♭-D-F#'),
('MI♭', 'Mi♭ Minore/Maggiore 7', 'Mi♭-Sol♭-Si♭-Re-Fa', 'Eb', 'Ebm/Maj7', 'Eb-G♭-B♭-D-F#'),
('MI♭', 'Mi♭ Settima 9#11', 'Mi♭-Sol-Si♭-Re♭-Fa-F♯', 'Eb', 'Eb9#11', 'Eb-G-B♭-Db-F-F#'),
('MI♭', 'Mi♭ Settima Minore 9', 'Mi♭-Sol♭-Si♭-Re♭-Fa♭', 'Eb', 'Ebm9', 'Eb-G♭-B♭-Db-F-Ab'),
('MI♭', 'Mi♭ Settima Maggiore 13', 'Mi♭-Sol-Si♭-Re-Fa-Fa♯-La♭', 'Eb', 'EbMaj13', 'Eb-G-B♭-D-F-F#-A♭'),
('MI♭', 'Mi♭ Minore 11', 'Mi♭-Sol-Si♭-Re♭-Fa-Fa♯-La♭', 'Eb', 'Ebm11', 'Eb-G♭-B♭-Db-F-Ab-B'),
('MI♭', 'Mi♭ Settima add11', 'Mi♭-Sol-Si♭-Re-Fa', 'Eb', 'Eb7add11', 'Eb-G-B♭-Db-F');

-- Creazione della tabella MIdiesis
CREATE TABLE NoteMIdiesis (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);

-- Inserimento dei dati per gli accordi di Mi# nella tabella MI#
INSERT INTO NoteMIdiesis (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('MI#', 'Mi# Maggiore', 'Mi#-Sol##-Si#', 'F', 'FMaj', 'F-A-C'),
('MI#', 'Mi# Minore', 'Mi#-Sol#-Si#', 'F', 'Fm', 'F-A♭-C'),
('MI#', 'Mi# Settima', 'Mi#-Sol##-Si#-Re#', 'F', 'F7', 'F-A-C-E'),
('MI#', 'Mi# Maggiore 7', 'Mi#-Sol##-Si#-Re##', 'F', 'FMaj7', 'F-A-C-E#'),
('MI#', 'Mi# Minore 7', 'Mi#-Sol#-Si#-Re#', 'F', 'Fm7', 'F-A♭-C-E'),
('MI#', 'Mi# Settima Minore', 'Mi#-Sol#-Si#-Re♭', 'F', 'Fm7', 'F-A♭-C-E'),
('MI#', 'Mi# Maggiore 6', 'Mi#-Sol##-Si#-La#', 'F', 'F6', 'F-A-C-D#'),
('MI#', 'Mi# Minore 6', 'Mi#-Sol#-Si#-La#', 'F', 'Fm6', 'F-A♭-C-D#'),
('MI#', 'Mi# Settima 9', 'Mi#-Sol##-Si#-Re#-Fa#', 'F', 'F9', 'F-A-C-E-F#'),
('MI#', 'Mi# Maggiore 9', 'Mi#-Sol##-Si#-Re##-Fa#', 'F', 'FMaj9', 'F-A-C-E-F#'),
('MI#', 'Mi# Minore 9', 'Mi#-Sol#-Si#-Re#-Fa#', 'F', 'Fm9', 'F-A♭-C-E-F#'),
('MI#', 'Mi# Settima Maggiore 7', 'Mi#-Sol##-Si#-Re##-Fa', 'F', 'FMaj7♯5', 'F-A-C-E-F##'),
('MI#', 'Mi# Diminuito', 'Mi#-Sol#-Si', 'F', 'Fdim', 'F-A♭-C♭'),
('MI#', 'Mi# Aumentato', 'Mi#-Sol##-Si##', 'F', 'Faug', 'F-A-C#'),
('MI#', 'Mi# Sesta', 'Mi#-Sol##-Si#-La#', 'F', 'F6', 'F-A-C-D#'),
('MI#', 'Mi# Nona', 'Mi#-Sol##-Si#-Re#-Fa#', 'F', 'F9', 'F-A-C-E-F#'),
('MI#', 'Mi# Settima Maggiore', 'Mi#-Sol##-Si#-Re##-Fa#', 'F', 'FMaj7', 'F-A-C-E-F#'),
('MI#', 'Mi# Settima Maggiore 9', 'Mi#-Sol##-Si#-Re##-Fa#-La#', 'F', 'FMaj9', 'F-A-C-E-F#-A#'),
('MI#', 'Mi# Settima 11', 'Mi#-Sol##-Si#-Re#-Fa#-La', 'F', 'F11', 'F-A-C-E-F#-A'),
('MI#', 'Mi# Settima 13', 'Mi#-Sol##-Si#-Re#-Fa#-La-Do#', 'F', 'F13', 'F-A-C-E-F#-A-C#'),
('MI#', 'Mi# Settima 9 Add11', 'Mi#-Sol##-Si#-Re#-Fa#-La#', 'F', 'F9add11', 'F-A-C-E-F#-A#'),
('MI#', 'Mi# Sesta 9', 'Mi#-Sol##-Si#-La#-Re#', 'F', 'F6/9', 'F-A-C-D#-G#'),
('MI#', 'Mi# Sesta 11', 'Mi#-Sol##-Si#-La#-Re#-Fa#', 'F', 'F6/11', 'F-A-C-D#-G#-B'),
('MI#', 'Mi# Settima Maggiore 11', 'Mi#-Sol##-Si#-Re##-Fa#-La#', 'F', 'FMaj7#11', 'F-A-C-E-F#-A#'),
('MI#', 'Mi# Minore 7 Add11', 'Mi#-Sol#-Si#-Re-Fa#', 'F', 'Fm7add11', 'F-A♭-C-E-F#'),
('MI#', 'Mi# Maggiore 7#11', 'Mi#-Sol##-Si#-Re-Fa#', 'F', 'FMaj7#11', 'F-A-C-E-F#'),
('MI#', 'Mi# Minore/Maggiore 7', 'Mi#-Sol#-Si#-Re-Fa#', 'F', 'Fm/Maj7', 'F-A♭-C-E-F#'),
('MI#', 'Mi# Settima 9#11', 'Mi#-Sol##-Si#-Re#-Fa#-La##', 'F', 'F9#11', 'F-A-C-E-F#-A##'),
('MI#', 'Mi# Settima Minore 9', 'Mi#-Sol#-Si#-Re♭-Fa#', 'F', 'Fm9', 'F-A♭-C-E-F#-A'),
('MI#', 'Mi# Settima Maggiore 13', 'Mi#-Sol##-Si#-Re##-Fa#-La#-Do##', 'F', 'FMaj13', 'F-A-C-E-F#-A#-D##'),
('MI#', 'Mi# Minore 11', 'Mi#-Sol#-Si#-Re#-Fa#-La#-Do#', 'F', 'Fm11', 'F-A♭-C-E-F#-A#-D#'),
('MI#', 'Mi# Settima add11', 'Mi#-Sol##-Si#-Re-Fa#-La#', 'F', 'F7add11', 'F-A-C-E-F#-A#');

-- Creazione della tabella FA
CREATE TABLE NoteFA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);
-- Inserimento dei dati per gli accordi di Fa nella tabella FA
INSERT INTO NoteFA (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('FA', 'Fa Maggiore', 'Fa-La-Do', 'F', 'FMaj', 'F-A-C'),
('FA', 'Fa Minore', 'Fa-La♭-Do', 'F', 'Fm', 'F-A♭-C'),
('FA', 'Fa Settima', 'Fa-La-Do-Mi♭', 'F', 'F7', 'F-A-C-E♭'),
('FA', 'Fa Maggiore 7', 'Fa-La-Do-Mi', 'F', 'FMaj7', 'F-A-C-E'),
('FA', 'Fa Minore 7', 'Fa-La♭-Do-Mi♭', 'F', 'Fm7', 'F-A♭-C-E♭'),
('FA', 'Fa Settima Minore', 'Fa-La♭-Do-Mi♭', 'F', 'Fm7', 'F-A♭-C-E♭'),
('FA', 'Fa Maggiore 6', 'Fa-La-Do-Re', 'F', 'F6', 'F-A-C-D'),
('FA', 'Fa Minore 6', 'Fa-La♭-Do-Re', 'F', 'Fm6', 'F-A♭-C-D'),
('FA', 'Fa Settima 9', 'Fa-La-Do-Mi♭-Sol', 'F', 'F9', 'F-A-C-E♭-G'),
('FA', 'Fa Maggiore 9', 'Fa-La-Do-Mi-Sol', 'F', 'FMaj9', 'F-A-C-E-G'),
('FA', 'Fa Minore 9', 'Fa-La♭-Do-Mi♭-Sol', 'F', 'Fm9', 'F-A♭-C-E♭-G'),
('FA', 'Fa Settima Maggiore 7', 'Fa-La-Do-Mi♯', 'F', 'FMaj7♯5', 'F-A-C-E♯'),
('FA', 'Fa Diminuito', 'Fa-La♭-Do♭', 'F', 'Fdim', 'F-A♭-C♭'),
('FA', 'Fa Aumentato', 'Fa-La-Do♯', 'F', 'Faug', 'F-A-C♯'),
('FA', 'Fa Sesta', 'Fa-La-Do-Re-Sol', 'F', 'F6', 'F-A-C-D-G'),
('FA', 'Fa Nona', 'Fa-La-Do-Mi-Sol-Re', 'F', 'F9', 'F-A-C-E-G-D'),
('FA', 'Fa Settima Maggiore', 'Fa-La-Do-Mi♯', 'F', 'FMaj7', 'F-A-C-E♯'),
('FA', 'Fa Settima Maggiore 9', 'Fa-La-Do-Mi♯-Sol', 'F', 'FMaj9', 'F-A-C-E♯-G'),
('FA', 'Fa Settima 11', 'Fa-La-Do-Mi♭-Sol-Si♭', 'F', 'F11', 'F-A-C-E♭-G-B♭'),
('FA', 'Fa Settima 13', 'Fa-La-Do-Mi♭-Sol-Si♭-Re', 'F', 'F13', 'F-A-C-E♭-G-B♭-D'),
('FA', 'Fa Settima 9 Add11', 'Fa-La-Do-Mi♭-Sol-Si♭', 'F', 'F9add11', 'F-A-C-E♭-G-B♭'),
('FA', 'Fa Sesta 9', 'Fa-La-Do-Re-Sol-Mi', 'F', 'F6/9', 'F-A-C-D-G-E'),
('FA', 'Fa Sesta 11', 'Fa-La-Do-Re-Sol-Mi-Fa', 'F', 'F6/11', 'F-A-C-D-G-E-F'),
('FA', 'Fa Settima Maggiore 11', 'Fa-La-Do-Mi♯-Sol-Si', 'F', 'FMaj7#11', 'F-A-C-E♯-G-B'),
('FA', 'Fa Minore 7 Add11', 'Fa-La♭-Do-Mi♭-Sol-Si♭', 'F', 'Fm7add11', 'F-A♭-C-E♭-G-B♭'),
('FA', 'Fa Maggiore 7#11', 'Fa-La-Do-Mi♯-Sol-Si', 'F', 'FMaj7#11', 'F-A-C-E♯-G-B'),
('FA', 'Fa Minore/Maggiore 7', 'Fa-La♭-Do-Mi♭-Sol-Si', 'F', 'Fm/Maj7', 'F-A♭-C-E♭-G-B'),
('FA', 'Fa Settima 9#11', 'Fa-La-Do-Mi♭-Sol-Si♭-Re', 'F', 'F9#11', 'F-A-C-E♭-G-B♭-D'),
('FA', 'Fa Settima Minore 9', 'Fa-La♭-Do-Mi♭-Sol-Si♭♭-Re♭', 'F', 'Fm9', 'F-A♭-C-E♭-G-B♭♭-D♭'),
('FA', 'Fa Settima Maggiore 13', 'Fa-La-Do-Mi♯-Sol-Si-Re-Fa', 'F', 'FMaj13', 'F-A-C-E♯-G-B-D-F'),
('FA', 'Fa Minore 11', 'Fa-La♭-Do-Mi♭-Sol-Si♭-Re-Fa', 'F', 'Fm11', 'F-A♭-C-E♭-G-B♭-D-F'),
('FA', 'Fa Settima add11', 'Fa-La-Do-Mi♭-Sol-Si', 'F', 'F7add11', 'F-A-C-E♭-G-B');

-- Creazione della tabella FAb
CREATE TABLE NoteFAb (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);
-- Inserimento dei dati per gli accordi di Fa♭ nella tabella FAb
INSERT INTO NoteFAb (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('FA♭', 'Fa♭ Maggiore', 'Fa♭-La♭-Do♭', 'E', 'EMaj', 'E-G♯-B'),
('FA♭', 'Fa♭ Minore', 'Fa♭-La♭♭-Do♭', 'E', 'Em', 'E-G-B♭'),
('FA♭', 'Fa♭ Settima', 'Fa♭-La♭♭-Do♭-Mi♭', 'E', 'E7', 'E-G-B♭-D'),
('FA♭', 'Fa♭ Maggiore 7', 'Fa♭-La♭-Do♭-Mi', 'E', 'EMaj7', 'E-G♯-B-D♯'),
('FA♭', 'Fa♭ Minore 7', 'Fa♭-La♭♭-Do♭-Mi♭', 'E', 'Em7', 'E-G-B♭-D'),
('FA♭', 'Fa♭ Settima Minore', 'Fa♭-La♭♭-Do♭-Mi♭♭', 'E', 'Em7', 'E-G-B♭-D'),
('FA♭', 'Fa♭ Maggiore 6', 'Fa♭-La♭-Do♭-Re♭', 'E', 'E6', 'E-G♯-B-C♯'),
('FA♭', 'Fa♭ Minore 6', 'Fa♭-La♭♭-Do♭-Re♭', 'E', 'Em6', 'E-G-B♭-C♯'),
('FA♭', 'Fa♭ Settima 9', 'Fa♭-La♭♭-Do♭-Mi♭-Sol♭', 'E', 'E9', 'E-G-B♭-D-F'),
('FA♭', 'Fa♭ Maggiore 9', 'Fa♭-La♭-Do♭-Mi-Sol', 'E', 'EMaj9', 'E-G♯-B-D♯-F♯'),
('FA♭', 'Fa♭ Minore 9', 'Fa♭-La♭♭-Do♭-Mi♭-Sol', 'E', 'Em9', 'E-G-B♭-D-F♯'),
('FA♭', 'Fa♭ Settima Maggiore 7', 'Fa♭-La♭-Do♭-Mi♯', 'E', 'EMaj7♯5', 'E-G♯-B-D♯'),
('FA♭', 'Fa♭ Diminuito', 'Fa♭-La♭♭-Do♭♭', 'E', 'Edim', 'E-G♭-B♭♭'),
('FA♭', 'Fa♭ Aumentato', 'Fa♭-La♭-Do', 'E', 'Eaug', 'E-G♯-B♯'),
('FA♭', 'Fa♭ Sesta', 'Fa♭-La♭-Do-Re♭', 'E', 'E6', 'E-G♯-B-C♯'),
('FA♭', 'Fa♭ Nona', 'Fa♭-La♭-Do-Mi-Sol-Re♭', 'E', 'E9', 'E-G♯-B-D-F♯-A'),
('FA♭', 'Fa♭ Settima Maggiore', 'Fa♭-La♭-Do-Mi♯', 'E', 'EMaj7', 'E-G♯-B-D♯'),
('FA♭', 'Fa♭ Settima Maggiore 9', 'Fa♭-La♭-Do-Mi♯-Sol', 'E', 'EMaj9', 'E-G♯-B-D♯-F♯'),
('FA♭', 'Fa♭ Settima 11', 'Fa♭-La♭-Do-Mi♭-Sol♭-Si♭', 'E', 'E11', 'E-G♯-B-D-F-A♭'),
('FA♭', 'Fa♭ Settima 13', 'Fa♭-La♭-Do-Mi♭-Sol♭-Si♭-Re♭', 'E', 'E13', 'E-G♯-B-D-F-A♭-C♭'),
('FA♭', 'Fa♭ Settima 9 Add11', 'Fa♭-La♭-Do-Mi♭-Sol♭-Si♭', 'E', 'E9add11', 'E-G♯-B-D-F-A♭'),
('FA♭', 'Fa♭ Sesta 9', 'Fa♭-La♭-Do-Re♭-Sol♭-Mi', 'E', 'E6/9', 'E-G♯-B-C♯-F-A'),
('FA♭', 'Fa♭ Sesta 11', 'Fa♭-La♭-Do-Re♭-Sol♭-Mi-Fa♭', 'E', 'E6/11', 'E-G♯-B-C♯-F-A-B♭'),
('FA♭', 'Fa♭ Settima Maggiore 11', 'Fa♭-La♭-Do-Mi♯-Sol-B', 'E', 'EMaj7#11', 'E-G♯-B-D♯-F♯-A'),
('FA♭', 'Fa♭ Minore 7 Add11', 'Fa♭-La♭♭-Do-Mi♭-Sol-B♭', 'E', 'Em7add11', 'E-G-B♭-D-F-A'),
('FA♭', 'Fa♭ Maggiore 7#11', 'Fa♭-La♭-Do-Mi♯-Sol-B', 'E', 'EMaj7#11', 'E-G♯-B-D♯-F♯-A'),
('FA♭', 'Fa♭ Minore/Maggiore 7', 'Fa♭-La♭♭-Do-Mi♭-Sol-B', 'E', 'Em/Maj7', 'E-G-B♭-D-F♯-A'),
('FA♭', 'Fa♭ Settima 9#11', 'Fa♭-La♭-Do-Mi♯-Sol-B♭-Re', 'E', 'E9#11', 'E-G♯-B-D♯-F♯-A♭-C'),
('FA♭', 'Fa♭ Settima Minore 9', 'Fa♭-La♭♭-Do-Mi♭-Sol-B♭♭-Re♭', 'E', 'Em9', 'E-G-B♭-D-F♯-A♭-C♭'),
('FA♭', 'Fa♭ Settima Maggiore 13', 'Fa♭-La♭-Do-Mi♯-Sol-B-D-Fa', 'E', 'EMaj13', 'E-G♯-B-D♯-F♯-A-C'),
('FA♭', 'Fa♭ Minore 11', 'Fa♭-La♭♭-Do-Mi♭-Sol-B♭-D-Fa', 'E', 'Em11', 'E-G-B♭-D-F♯-A-C'),
('FA♭', 'Fa♭ Settima add11', 'Fa♭-La♭-Do-Mi♭-Sol-B♭', 'E', 'E7add11', 'E-G♯-B-D-F♯-A♭');

-- Creazione della tabella FAdiesis
CREATE TABLE NoteFAdiesis (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);
-- Inserimento dei dati per gli accordi di Fa# nella tabella FA#
INSERT INTO NoteFA# (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('FA#', 'Fa# Maggiore', 'Fa#-La#-Do#', 'F#', 'F#Maj', 'F#-A#-C#'),
('FA#', 'Fa# Minore', 'Fa#-La-Do#', 'F#', 'F#m', 'F#-A-C#'),
('FA#', 'Fa# Settima', 'Fa#-La#-Do#-Mi', 'F#', 'F#7', 'F#-A#-C#-E'),
('FA#', 'Fa# Maggiore 7', 'Fa#-La#-Do#-Mi#', 'F#', 'F#Maj7', 'F#-A#-C#-E#'),
('FA#', 'Fa# Minore 7', 'Fa#-La-Do#-Mi', 'F#', 'F#m7', 'F#-A-C#-E'),
('FA#', 'Fa# Settima Minore', 'Fa#-La-Do#-Mi', 'F#', 'F#m7', 'F#-A-C#-E'),
('FA#', 'Fa# Maggiore 6', 'Fa#-La#-Do#-Re#', 'F#', 'F#6', 'F#-A#-C#-D#'),
('FA#', 'Fa# Minore 6', 'Fa#-La-Do#-Re', 'F#', 'F#m6', 'F#-A-C#-D'),
('FA#', 'Fa# Settima 9', 'Fa#-La#-Do#-Mi-So#', 'F#', 'F#9', 'F#-A#-C#-E-G#'),
('FA#', 'Fa# Maggiore 9', 'Fa#-La#-Do#-Mi#-So#', 'F#', 'F#Maj9', 'F#-A#-C#-E#-G#'),
('FA#', 'Fa# Minore 9', 'Fa#-La-Do#-Mi-So#', 'F#', 'F#m9', 'F#-A-C#-E-G#'),
('FA#', 'Fa# Settima Maggiore 7', 'Fa#-La#-Do#-Mi#', 'F#', 'F#Maj7♯5', 'F#-A#-C#-E#'),
('FA#', 'Fa# Diminuito', 'Fa#-La-Do', 'F#', 'F#dim', 'F#-A-C'),
('FA#', 'Fa# Aumentato', 'Fa#-La#-Do', 'F#', 'F#aug', 'F#-A#-C'),
('FA#', 'Fa# Sesta', 'Fa#-La#-Do#-Re#-So#', 'F#', 'F#6', 'F#-A#-C#-D#-G#'),
('FA#', 'Fa# Nona', 'Fa#-La#-Do#-Mi-So#-Re#', 'F#', 'F#9', 'F#-A#-C#-E-G#-D#'),
('FA#', 'Fa# Settima Maggiore', 'Fa#-La#-Do#-Mi#', 'F#', 'F#Maj7', 'F#-A#-C#-E#'),
('FA#', 'Fa# Settima Maggiore 9', 'Fa#-La#-Do#-Mi#-So#', 'F#', 'F#Maj9', 'F#-A#-C#-E#-G#'),
('FA#', 'Fa# Settima 11', 'Fa#-La#-Do#-Mi-So#-Si', 'F#', 'F#11', 'F#-A#-C#-E-G#-B'),
('FA#', 'Fa# Settima 13', 'Fa#-La#-Do#-Mi-So#-Si-Re#', 'F#', 'F#13', 'F#-A#-C#-E-G#-B-D#'),
('FA#', 'Fa# Settima 9 Add11', 'Fa#-La#-Do#-Mi-So#-Si', 'F#', 'F#9add11', 'F#-A#-C#-E-G#-B'),
('FA#', 'Fa# Sesta 9', 'Fa#-La#-Do#-Re#-So#-Mi', 'F#', 'F#6/9', 'F#-A#-C#-D#-G#-E'),
('FA#', 'Fa# Sesta 11', 'Fa#-La#-Do#-Re#-So#-Mi-Fa#', 'F#', 'F#6/11', 'F#-A#-C#-D#-G#-E-F#'),
('FA#', 'Fa# Settima Maggiore 11', 'Fa#-La#-Do#-Mi#-So#-Si#', 'F#', 'F#Maj7#11', 'F#-A#-C#-E#-G#-B'),
('FA#', 'Fa# Minore 7 Add11', 'Fa#-La-Do#-Mi-So#-Si#', 'F#', 'F#m7add11', 'F#-A-C#-E-G#-B'),
('FA#', 'Fa# Maggiore 7#11', 'Fa#-La#-Do#-Mi#-So#-Si#', 'F#', 'F#Maj7#11', 'F#-A#-C#-E#-G#-B'),
('FA#', 'Fa# Minore/Maggiore 7', 'Fa#-La-Do#-Mi-So#-Si#', 'F#', 'F#m/Maj7', 'F#-A-C#-E-G#-B'),
('FA#', 'Fa# Settima 9#11', 'Fa#-La#-Do#-Mi-So#-Si♭-Re#', 'F#', 'F#9#11', 'F#-A#-C#-E-G#-B♭-D#'),
('FA#', 'Fa# Settima Minore 9', 'Fa#-La-Do#-Mi-So#-Si-Do#', 'F#', 'F#m9', 'F#-A-C#-E-G#-B-D#'),
('FA#', 'Fa# Settima Maggiore 13', 'Fa#-La#-Do#-Mi#-So#-Si-Re#', 'F#', 'F#Maj13', 'F#-A#-C#-E#-G#-B-D#'),
('FA#', 'Fa# Minore 11', 'Fa#-La-Do#-Mi-So#-Si-Do#-Re#', 'F#', 'F#m11', 'F#-A-C#-E-G#-B-D#-F#'),
('FA#', 'Fa# Settima add11', 'Fa#-La#-Do#-Mi-So#-Si', 'F#', 'F#7add11', 'F#-A#-C#-E-G#-B');

-- Creazione della tabella SOL
CREATE TABLE NoteSOL (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);
-- Inserimento dei dati per gli accordi di Sol nella tabella SOL
INSERT INTO NoteSOL (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('SOL', 'Sol Maggiore', 'Sol-Si-Re', 'G', 'GMaj', 'G-B-D'),
('SOL', 'Sol Minore', 'Sol-Si♭-Re', 'G', 'Gm', 'G-B♭-D'),
('SOL', 'Sol Settima', 'Sol-Si-Re-Fa', 'G', 'G7', 'G-B-D-F'),
('SOL', 'Sol Maggiore 7', 'Sol-Si-Re-Fa#', 'G', 'GMaj7', 'G-B-D-F#'),
('SOL', 'Sol Minore 7', 'Sol-Si♭-Re-Fa', 'G', 'Gm7', 'G-B♭-D-F'),
('SOL', 'Sol Settima Minore', 'Sol-Si♭-Re-Fa', 'G', 'Gm7', 'G-B♭-D-F'),
('SOL', 'Sol Maggiore 6', 'Sol-Si-Re-La', 'G', 'G6', 'G-B-D-A'),
('SOL', 'Sol Minore 6', 'Sol-Si♭-Re-La', 'G', 'Gm6', 'G-B♭-D-A'),
('SOL', 'Sol Settima 9', 'Sol-Si-Re-Fa-La', 'G', 'G9', 'G-B-D-F-A'),
('SOL', 'Sol Maggiore 9', 'Sol-Si-Re-Fa#-La', 'G', 'GMaj9', 'G-B-D-F#-A'),
('SOL', 'Sol Minore 9', 'Sol-Si♭-Re-Fa-A♭', 'G', 'Gm9', 'G-B♭-D-F-A♭'),
('SOL', 'Sol Settima Maggiore 7', 'Sol-Si-Re-Fa#', 'G', 'GMaj7♯5', 'G-B-D-F#'),
('SOL', 'Sol Diminuito', 'Sol-Si♭-Re♭', 'G', 'Gdim', 'G-B♭-D♭'),
('SOL', 'Sol Aumentato', 'Sol-Si-Re♯', 'G', 'Gaug', 'G-B-D♯'),
('SOL', 'Sol Sesta', 'Sol-Si-Re-La', 'G', 'G6', 'G-B-D-A'),
('SOL', 'Sol Nona', 'Sol-Si-Re-Fa-La', 'G', 'G9', 'G-B-D-F-A'),
('SOL', 'Sol Settima Maggiore', 'Sol-Si-Re-Fa#', 'G', 'GMaj7', 'G-B-D-F#'),
('SOL', 'Sol Settima Maggiore 9', 'Sol-Si-Re-Fa#-La', 'G', 'GMaj9', 'G-B-D-F#-A'),
('SOL', 'Sol Settima 11', 'Sol-Si-Re-Fa-La-Do', 'G', 'G11', 'G-B-D-F-A-C'),
('SOL', 'Sol Settima 13', 'Sol-Si-Re-Fa-La-Do-Mi', 'G', 'G13', 'G-B-D-F-A-C-E'),
('SOL', 'Sol Settima 9 Add11', 'Sol-Si-Re-Fa-La-Do', 'G', 'G9add11', 'G-B-D-F-A-C'),
('SOL', 'Sol Sesta 9', 'Sol-Si-Re-La-Fa', 'G', 'G6/9', 'G-B-D-A-F'),
('SOL', 'Sol Sesta 11', 'Sol-Si-Re-La-Fa-Do', 'G', 'G6/11', 'G-B-D-A-F-C'),
('SOL', 'Sol Settima Maggiore 11', 'Sol-Si-Re-Fa#-Do', 'G', 'GMaj7#11', 'G-B-D-F#-C'),
('SOL', 'Sol Minore 7 Add11', 'Sol-Si♭-Re-Fa-La', 'G', 'Gm7add11', 'G-B♭-D-F-A'),
('SOL', 'Sol Maggiore 7#11', 'Sol-Si-Re-Fa#-Do#', 'G', 'GMaj7#11', 'G-B-D-F#-C#'),
('SOL', 'Sol Minore/Maggiore 7', 'Sol-Si♭-Re-Fa#-Do', 'G', 'Gm/Maj7', 'G-B♭-D-F#-C'),
('SOL', 'Sol Settima 9#11', 'Sol-Si-Re-Fa-La-Do#', 'G', 'G9#11', 'G-B-D-F-A-C#'),
('SOL', 'Sol Settima Minore 9', 'Sol-Si♭-Re-Fa-A♭-Do', 'G', 'Gm9', 'G-B♭-D-F-A♭-C'),
('SOL', 'Sol Settima Maggiore 13', 'Sol-Si-Re-Fa#-La-Do#-Mi', 'G', 'GMaj13', 'G-B-D-F#-A-C#-E'),
('SOL', 'Sol Minore 11', 'Sol-Si♭-Re-Fa-A♭-Do-Mi♭', 'G', 'Gm11', 'G-B♭-D-F-A♭-C-E♭'),
('SOL', 'Sol Settima add11', 'Sol-Si-Re-Fa-La-Do', 'G', 'G7add11', 'G-B-D-F-A-C');

-- Creazione della tabella SOLb
CREATE TABLE NoteSOLb (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);
-- Inserimento dei dati per gli accordi di Solb nella tabella SOLb
INSERT INTO NoteSOLb (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('SOL♭', 'Sol♭ Maggiore', 'Sol♭-La♭♭-Do♭', 'F#', 'F#Maj', 'F#-A-C'),
('SOL♭', 'Sol♭ Minore', 'Sol♭-La♭♭-Do', 'F#', 'F#m', 'F#-A-C#'),
('SOL♭', 'Sol♭ Settima', 'Sol♭-La♭♭-Do♭-Mi♭♭', 'F#', 'F#7', 'F#-A-C-E'),
('SOL♭', 'Sol♭ Maggiore 7', 'Sol♭-La♭♭-Do♭-Mi♭', 'F#', 'F#Maj7', 'F#-A-C♯-E♯'),
('SOL♭', 'Sol♭ Minore 7', 'Sol♭-La♭♭-Do-Mi♭', 'F#', 'F#m7', 'F#-A-C#-E'),
('SOL♭', 'Sol♭ Settima Minore', 'Sol♭-La♭♭-Do-Mi♭', 'F#', 'F#m7', 'F#-A-C#-E'),
('SOL♭', 'Sol♭ Maggiore 6', 'Sol♭-La♭♭-Do♭-Re♭', 'F#', 'F#6', 'F#-A-C-D'),
('SOL♭', 'Sol♭ Minore 6', 'Sol♭-La♭♭-Do-Re♭', 'F#', 'F#m6', 'F#-A-C#-D'),
('SOL♭', 'Sol♭ Settima 9', 'Sol♭-La♭♭-Do♭-Mi♭-Sol♭', 'F#', 'F#9', 'F#-A-C-E-G'),
('SOL♭', 'Sol♭ Maggiore 9', 'Sol♭-La♭♭-Do♭-Mi♭♭-Sol♭', 'F#', 'F#Maj9', 'F#-A-C♯-E♯-G♯'),
('SOL♭', 'Sol♭ Minore 9', 'Sol♭-La♭♭-Do-Mi♭♭-Sol♭', 'F#', 'F#m9', 'F#-A-C#-E-G'),
('SOL♭', 'Sol♭ Settima Maggiore 7', 'Sol♭-La♭♭-Do♭-Mi♭♭-Sol♭', 'F#', 'F#Maj7♯5', 'F#-A-C♯-E♯-G♯'),
('SOL♭', 'Sol♭ Diminuito', 'Sol♭-La♭♭-Do♭♭', 'F#', 'F#dim', 'F#-A♭-C'),
('SOL♭', 'Sol♭ Aumentato', 'Sol♭-La♭♭-Do', 'F#', 'F#aug', 'F#-A-C♯'),
('SOL♭', 'Sol♭ Sesta', 'Sol♭-La♭♭-Do♭-Re♭-Sol♭', 'F#', 'F#6', 'F#-A-C-D-G'),
('SOL♭', 'Sol♭ Nona', 'Sol♭-La♭♭-Do♭-Mi♭-Sol♭-Si♭', 'F#', 'F#9', 'F#-A-C-E-G-B♭'),
('SOL♭', 'Sol♭ Settima Maggiore', 'Sol♭-La♭♭-Do♭-Mi♭♭-Sol♭', 'F#', 'F#Maj7', 'F#-A-C♯-E♯-G♯'),
('SOL♭', 'Sol♭ Settima Maggiore 9', 'Sol♭-La♭♭-Do♭-Mi♭♭-Sol♭-Si♭', 'F#', 'F#Maj9', 'F#-A-C♯-E♯-G♯-B♭'),
('SOL♭', 'Sol♭ Settima 11', 'Sol♭-La♭♭-Do♭-Mi♭-Sol♭-Si♭-Re♭', 'F#', 'F#11', 'F#-A-C-E-G-B♭-D'),
('SOL♭', 'Sol♭ Settima 13', 'Sol♭-La♭♭-Do♭-Mi♭-Sol♭-Si♭-Re♭-Fa', 'F#', 'F#13', 'F#-A-C-E-G-B♭-D-F'),
('SOL♭', 'Sol♭ Settima 9 Add11', 'Sol♭-La♭♭-Do♭-Mi♭-Sol♭-Si♭-Re♭', 'F#', 'F#9add11', 'F#-A-C-E-G-B♭-D'),
('SOL♭', 'Sol♭ Sesta 9', 'Sol♭-La♭♭-Do♭-Re♭-Sol♭-Mi♭', 'F#', 'F#6/9', 'F#-A-C-D-G-E'),
('SOL♭', 'Sol♭ Sesta 11', 'Sol♭-La♭♭-Do♭-Re♭-Sol♭-Mi♭-Fa', 'F#', 'F#6/11', 'F#-A-C-D-G-F'),
('SOL♭', 'Sol♭ Settima Maggiore 11', 'Sol♭-La♭♭-Do♭-Mi♭-Sol♭-Si♭-Fa', 'F#', 'F#Maj7#11', 'F#-A-C♯-E♯-G♯-B♭-F'),
('SOL♭', 'Sol♭ Minore 7 Add11', 'Sol♭-La♭♭-Do♭-Mi-So♭', 'F#', 'F#m7add11', 'F#-A-C#-E-G-B♭-F'),
('SOL♭', 'Sol♭ Maggiore 7#11', 'Sol♭-La♭♭-Do♭-Mi♭-So♭-Si♭-Fa#', 'F#', 'F#Maj7#11', 'F#-A-C♯-E♯-G♯-B-F#'),
('SOL♭', 'Sol♭ Minore/Maggiore 7', 'Sol♭-La♭♭-Do♭-Mi♭-So♭-Si♭-Fa', 'F#', 'F#m/Maj7', 'F#-A-C#-E♯-G♯-B-F'),
('SOL♭', 'Sol♭ Settima 9#11', 'Sol♭-La♭♭-Do♭-Mi♭-So♭-Si♭-Fa#', 'F#', 'F#9#11', 'F#-A-C-E-G-B-F#'),
('SOL♭', 'Sol♭ Settima Minore 9', 'Sol♭-La♭♭-Do♭-Mi-So♭-Si♭-Fa', 'F#', 'F#m9', 'F#-A-C#-E-G-B-F'),
('SOL♭', 'Sol♭ Settima Maggiore 13', 'Sol♭-La♭♭-Do♭-Mi♭-So♭-Si♭-Fa#-La#', 'F#', 'F#Maj13', 'F#-A-C♯-E♯-G♯-B-F#-A#'),
('SOL♭', 'Sol♭ Minore 11', 'Sol♭-La♭♭-Do♭-Mi-So♭-Si♭-Fa-La', 'F#', 'F#m11', 'F#-A-C#-E-G-B-F#-A'),
('SOL♭', 'Sol♭ Settima add11', 'Sol♭-La♭♭-Do♭-Mi♭-So♭-Si♭-Fa#', 'F#', 'F#7add11', 'F#-A-C-E-G-B-F#');

-- Creazione della tabella SOLdiesis
CREATE TABLE NoteSOLdiesis (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);
-- Inserimento dei dati per gli accordi di Sol# nella tabella SOL#
INSERT INTO NoteSOLdiesis (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('SOL#', 'Sol# Maggiore', 'Sol#-Si#-Re#', 'G#', 'G#Maj', 'G#-B#-D#'),
('SOL#', 'Sol# Minore', 'Sol#-Si-Mi', 'G#', 'G#m', 'G#-B-D#'),
('SOL#', 'Sol# Settima', 'Sol#-Si#-Re#-Fa#', 'G#', 'G#7', 'G#-B#-D#-F#'),
('SOL#', 'Sol# Maggiore 7', 'Sol#-Si#-Re#-Fa##', 'G#', 'G#Maj7', 'G#-B#-D#-F##'),
('SOL#', 'Sol# Minore 7', 'Sol#-Si-Mi-Fa#', 'G#', 'G#m7', 'G#-B-D#-F#'),
('SOL#', 'Sol# Settima Minore', 'Sol#-Si-Mi-Fa#', 'G#', 'G#m7', 'G#-B-D#-F#'),
('SOL#', 'Sol# Maggiore 6', 'Sol#-Si#-Re#-La#', 'G#', 'G#6', 'G#-B#-D#-A#'),
('SOL#', 'Sol# Minore 6', 'Sol#-Si-Mi-La#', 'G#', 'G#m6', 'G#-B-D#-A#'),
('SOL#', 'Sol# Settima 9', 'Sol#-Si#-Re#-Fa#-La#', 'G#', 'G#9', 'G#-B#-D#-F#-A#'),
('SOL#', 'Sol# Maggiore 9', 'Sol#-Si#-Re#-Fa##-La#', 'G#', 'G#Maj9', 'G#-B#-D#-F##-A#'),
('SOL#', 'Sol# Minore 9', 'Sol#-Si-Mi-Fa#-La#', 'G#', 'G#m9', 'G#-B-D#-F#-A#'),
('SOL#', 'Sol# Settima Maggiore 7', 'Sol#-Si#-Re#-Fa##-La#', 'G#', 'G#Maj7♯5', 'G#-B#-D#-F##-A#'),
('SOL#', 'Sol# Diminuito', 'Sol#-Si-Mi-Fa', 'G#', 'G#dim', 'G#-B-D-F'),
('SOL#', 'Sol# Aumentato', 'Sol#-Si#-Re##-Fa##', 'G#', 'G#aug', 'G#-B#-D##-F##'),
('SOL#', 'Sol# Sesta', 'Sol#-Si#-Re#-La#', 'G#', 'G#6', 'G#-B#-D#-A#'),
('SOL#', 'Sol# Nona', 'Sol#-Si#-Re#-Fa#-La#-Do#', 'G#', 'G#9', 'G#-B#-D#-F#-A#-C#'),
('SOL#', 'Sol# Settima Maggiore', 'Sol#-Si#-Re#-Fa##-La#-Do#', 'G#', 'G#Maj7', 'G#-B#-D#-F##-A#-C#'),
('SOL#', 'Sol# Settima Maggiore 9', 'Sol#-Si#-Re#-Fa##-La#-Do#-Mi#', 'G#', 'G#Maj9', 'G#-B#-D#-F##-A#-C#-E#'),
('SOL#', 'Sol# Settima 11', 'Sol#-Si#-Re#-Fa#-La#-Do#-Mi#-Sol', 'G#', 'G#11', 'G#-B#-D#-F#-A#-C#-E#-G#'),
('SOL#', 'Sol# Settima 13', 'Sol#-Si#-Re#-Fa#-La#-Do#-Mi#-Sol-Si', 'G#', 'G#13', 'G#-B#-D#-F#-A#-C#-E#-G#-B#'),
('SOL#', 'Sol# Settima 9 Add11', 'Sol#-Si#-Re#-Fa#-La#-Do#-Mi#-Sol', 'G#', 'G#9add11', 'G#-B#-D#-F#-A#-C#-E#-G#'),
('SOL#', 'Sol# Sesta 9', 'Sol#-Si#-Re#-La#-Mi#', 'G#', 'G#6/9', 'G#-B#-D#-A#-F#'),
('SOL#', 'Sol# Sesta 11', 'Sol#-Si#-Re#-La#-Mi#-Sol', 'G#', 'G#6/11', 'G#-B#-D#-A#-F#-C#'),
('SOL#', 'Sol# Settima Maggiore 11', 'Sol#-Si#-Re#-Fa##-Do#', 'G#', 'G#Maj7#11', 'G#-B#-D#-F##-C#'),
('SOL#', 'Sol# Minore 7 Add11', 'Sol#-Si-Re#-Fa#-La#', 'G#', 'G#m7add11', 'G#-B-D#-F#-A#-C#'),
('SOL#', 'Sol# Maggiore 7#11', 'Sol#-Si#-Re#-Fa##-La#-Do##', 'G#', 'G#Maj7#11', 'G#-B#-D#-F##-A#-C##'),
('SOL#', 'Sol# Minore/Maggiore 7', 'Sol#-Si-Re#-Fa#-La#-Do#', 'G#', 'G#m/Maj7', 'G#-B-D#-F#-A#-C#'),
('SOL#', 'Sol# Settima 9#11', 'Sol#-Si#-Re#-Fa#-La#-Do#-Mi#-Sol', 'G#', 'G#9#11', 'G#-B#-D#-F#-A#-C#-E#-G#'),
('SOL#', 'Sol# Settima Minore 9', 'Sol#-Si-Re#-Fa#-La#-Do#-Mi#-Sol', 'G#', 'G#m9', 'G#-B-D#-F#-A#-C#-E#-G#'),
('SOL#', 'Sol# Settima Maggiore 13', 'Sol#-Si#-Re#-Fa#-La#-Do#-Mi#-Sol-Si', 'G#', 'G#Maj13', 'G#-B#-D#-F#-A#-C#-E#-G#-B#'),
('SOL#', 'Sol# Minore 11', 'Sol#-Si-Re#-Fa#-La#-Do#-Mi#-Sol-Si', 'G#', 'G#m11', 'G#-B-D#-F#-A#-C#-E#-G#-B'),
('SOL#', 'Sol# Settima add11', 'Sol#-Si#-Re#-Fa#-La#-Do#-Mi#-Sol', 'G#', 'G#7add11', 'G#-B#-D#-F#-A#-C#-E#-G#');

-- Creazione della tabella LA
CREATE TABLE NoteLA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);
-- Inserimento dei dati per gli accordi di La nella tabella LA
INSERT INTO NoteLA (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('LA', 'La Maggiore', 'La-Do#-Mi', 'A', 'AMaj', 'A-C#-E'),
('LA', 'La Minore', 'La-Do-Mi', 'A', 'Am', 'A-C-E'),
('LA', 'La Settima', 'La-Do#-Mi-Sol', 'A', 'A7', 'A-C#-E-G'),
('LA', 'La Maggiore 7', 'La-Do#-Mi-Sol#', 'A', 'AMaj7', 'A-C#-E-G#'),
('LA', 'La Minore 7', 'La-Do-Mi-Sol', 'A', 'Am7', 'A-C-E-G'),
('LA', 'La Settima Minore', 'La-Do-Mi-Sol', 'A', 'Am7', 'A-C-E-G'),
('LA', 'La Maggiore 6', 'La-Do#-Mi-Fa#', 'A', 'A6', 'A-C#-E-F#'),
('LA', 'La Minore 6', 'La-Do-Mi-Fa#', 'A', 'Am6', 'A-C-E-F#'),
('LA', 'La Settima 9', 'La-Do#-Mi-Sol-Si', 'A', 'A9', 'A-C#-E-G-B'),
('LA', 'La Maggiore 9', 'La-Do#-Mi-Sol#-Si', 'A', 'AMaj9', 'A-C#-E-G#-B'),
('LA', 'La Minore 9', 'La-Do-Mi-Sol-Si', 'A', 'Am9', 'A-C-E-G-B'),
('LA', 'La Settima Maggiore 7', 'La-Do#-Mi-Sol#-Si', 'A', 'AMaj7♯5', 'A-C#-E-G#-B'),
('LA', 'La Diminuito', 'La-Do-Mi♭-Sol', 'A', 'Adim', 'A-C-E♭-G'),
('LA', 'La Aumentato', 'La-Do#-Mi-Sol#', 'A', 'Aaug', 'A-C#-E♭-G#'),
('LA', 'La Sesta', 'La-Do#-Mi-Fa#-Si', 'A', 'A6', 'A-C#-E-F#-B'),
('LA', 'La Nona', 'La-Do#-Mi-Sol-Si-Re', 'A', 'A9', 'A-C#-E-G-B-D'),
('LA', 'La Settima Maggiore', 'La-Do#-Mi-Sol#-Si', 'A', 'AMaj7', 'A-C#-E-G#-B'),
('LA', 'La Settima Maggiore 9', 'La-Do#-Mi-Sol#-Si-Re', 'A', 'AMaj9', 'A-C#-E-G#-B-D'),
('LA', 'La Settima 11', 'La-Do#-Mi-Sol#-Si-Re-Fa#', 'A', 'A11', 'A-C#-E-G#-B-D-F#'),
('LA', 'La Settima 13', 'La-Do#-Mi-Sol#-Si-Re-Fa#-La', 'A', 'A13', 'A-C#-E-G#-B-D-F#-A'),
('LA', 'La Settima 9 Add11', 'La-Do#-Mi-Sol#-Si-Re-Fa#', 'A', 'A9add11', 'A-C#-E-G#-B-D-F#'),
('LA', 'La Sesta 9', 'La-Do#-Mi-Fa#-Si-Re', 'A', 'A6/9', 'A-C#-E-F#-B-D'),
('LA', 'La Sesta 11', 'La-Do#-Mi-Fa#-Si-Re-Fa', 'A', 'A6/11', 'A-C#-E-F#-B-D-F'),
('LA', 'La Settima Maggiore 11', 'La-Do#-Mi-Sol#-Si-Fa', 'A', 'AMaj7#11', 'A-C#-E-G#-B-F#'),
('LA', 'La Minore 7 Add11', 'La-Do-Mi-Sol-B♭', 'A', 'Am7add11', 'A-C-E-G-B♭-F'),
('LA', 'La Maggiore 7#11', 'La-Do#-Mi-Sol#-Si-F♯', 'A', 'AMaj7#11', 'A-C#-E-G#-B-F♯'),
('LA', 'La Minore/Maggiore 7', 'La-Do-Mi-Sol-B', 'A', 'Am/Maj7', 'A-C-E-G-B'),
('LA', 'La Settima 9#11', 'La-Do#-Mi-Sol#-Si-F♯', 'A', 'A9#11', 'A-C#-E-G#-B-F♯'),
('LA', 'La Settima Minore 9', 'La-Do-Mi-Sol-B♭-Si', 'A', 'Am9', 'A-C-E-G-B♭-D'),
('LA', 'La Settima Maggiore 13', 'La-Do#-Mi-Sol#-Si-Re-F♯-La', 'A', 'AMaj13', 'A-C#-E-G#-B-D-F♯-A'),
('LA', 'La Minore 11', 'La-Do-Mi-Sol-B♭-Si-Re-Fa', 'A', 'Am11', 'A-C-E-G-B♭-D-F'),
('LA', 'La Settima add11', 'La-Do#-Mi-Sol#-Si-Fa#', 'A', 'A7add11', 'A-C#-E-G#-B-D-F#');

-- Creazione della tabella LAb
CREATE TABLE NoteLAb (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);
-- Inserimento dei dati per gli accordi di Lab nella tabella LAb
INSERT INTO NoteLAb (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('LAb', 'Lab Maggiore', 'Lab-Do-Mib', 'Ab', 'AbMaj', 'Ab-C-Eb'),
('LAb', 'Lab Minore', 'Lab-Do♭-Mib', 'Ab', 'Abm', 'Ab-C♭-Eb'),
('LAb', 'Lab Settima', 'Lab-Do-Mib-Solb', 'Ab', 'Ab7', 'Ab-C♭-Eb-G♭'),
('LAb', 'Lab Maggiore 7', 'Lab-Do-Mib-Sol', 'Ab', 'AbMaj7', 'Ab-C-Eb-G'),
('LAb', 'Lab Minore 7', 'Lab-Do♭-Mib-Sol♭', 'Ab', 'Abm7', 'Ab-C♭-Eb-G♭'),
('LAb', 'Lab Settima Minore', 'Lab-Do♭-Mib-Solb', 'Ab', 'Abm7', 'Ab-C♭-Eb-G♭'),
('LAb', 'Lab Maggiore 6', 'Lab-Do-Mib-Fa', 'Ab', 'Ab6', 'Ab-C-Eb-F'),
('LAb', 'Lab Minore 6', 'Lab-Do♭-Mib-Fa', 'Ab', 'Abm6', 'Ab-C♭-Eb-F'),
('LAb', 'Lab Settima 9', 'Lab-Do-Mib-Solb-Tib', 'Ab', 'Ab9', 'Ab-C-Eb-G♭-B♭'),
('LAb', 'Lab Maggiore 9', 'Lab-Do-Mib-Sol-Ti', 'Ab', 'AbMaj9', 'Ab-C-Eb-G-B'),
('LAb', 'Lab Minore 9', 'Lab-Do♭-Mib-Sol♭-Ti', 'Ab', 'Abm9', 'Ab-C♭-Eb-G♭-B'),
('LAb', 'Lab Settima Maggiore 7', 'Lab-Do-Mib-Sol-Tib', 'Ab', 'AbMaj7♯5', 'Ab-C-Eb-G-B♭'),
('LAb', 'Lab Diminuito', 'Lab-Do♭-Mib♭-Sol♭', 'Ab', 'Abdim', 'Ab-C♭-Eb♭-G♭'),
('LAb', 'Lab Aumentato', 'Lab-Do-Mib♯-Sol', 'Ab', 'Abaug', 'Ab-C-E♭-G♯'),
('LAb', 'Lab Sesta', 'Lab-Do-Mib-Fa-Lab', 'Ab', 'Ab6', 'Ab-C-Eb-F-Ab'),
('LAb', 'Lab Nona', 'Lab-Do-Mib-Solb-Tib-Reb', 'Ab', 'Ab9', 'Ab-C-Eb-G♭-B♭-D♭'),
('LAb', 'Lab Settima Maggiore', 'Lab-Do-Mib-Sol-Ti-Re', 'Ab', 'AbMaj7', 'Ab-C-Eb-G-B-D'),
('LAb', 'Lab Settima Maggiore 9', 'Lab-Do-Mib-Sol-Ti-Reb', 'Ab', 'AbMaj9', 'Ab-C-Eb-G-B-D♭'),
('LAb', 'Lab Settima 11', 'Lab-Do-Mib-Sol-Tib-Reb-Fa', 'Ab', 'Ab11', 'Ab-C-Eb-G♭-B♭-D♭-F'),
('LAb', 'Lab Settima 13', 'Lab-Do-Mib-Sol-Tib-Reb-Fa-Lab', 'Ab', 'Ab13', 'Ab-C-Eb-G♭-B♭-D♭-F-Ab'),
('LAb', 'Lab Settima 9 Add11', 'Lab-Do-Mib-Sol-Tib-Reb-Fa', 'Ab', 'Ab9add11', 'Ab-C-Eb-G♭-B♭-D♭-F'),
('LAb', 'Lab Sesta 9', 'Lab-Do-Mib-Fa-Lab-Tib', 'Ab', 'Ab6/9', 'Ab-C-Eb-F-Ab-D♭'),
('LAb', 'Lab Sesta 11', 'Lab-Do-Mib-Fa-Lab-Tib-Reb', 'Ab', 'Ab6/11', 'Ab-C-Eb-F-Ab-D♭-F'),
('LAb', 'Lab Settima Maggiore 11', 'Lab-Do-Mib-Sol-Ti-Re-Fa', 'Ab', 'AbMaj7#11', 'Ab-C-Eb-G-B-D♭-F'),
('LAb', 'Lab Minore 7 Add11', 'Lab-Do♭-Mib-Fa-Solb', 'Ab', 'Abm7add11', 'Ab-C♭-Eb-F-G♭-D♭'),
('LAb', 'Lab Maggiore 7#11', 'Lab-Do-Mib-Sol-Ti-Fa♯', 'Ab', 'AbMaj7#11', 'Ab-C-Eb-G-B-D♭-F♯'),
('LAb', 'Lab Minore/Maggiore 7', 'Lab-Do♭-Mib-Fa-Sol', 'Ab', 'Abm/Maj7', 'Ab-C♭-Eb-F-G'),
('LAb', 'Lab Settima 9#11', 'Lab-Do-Mib-Sol-Tib-Re-Fa♯', 'Ab', 'Ab9#11', 'Ab-C-Eb-G♭-B♭-D♭-F♯'),
('LAb', 'Lab Settima Minore 9', 'Lab-Do♭-Mib-Sol♭-Ti-Re', 'Ab', 'Abm9', 'Ab-C♭-Eb-G♭-B♭-D♭'),
('LAb', 'Lab Settima Maggiore 13', 'Lab-Do-Mib-Sol-Ti-Reb-Fa♯-Lab', 'Ab', 'AbMaj13', 'Ab-C-Eb-G-B-D♭-F♯-Ab'),
('LAb', 'Lab Minore 11', 'Lab-Do♭-Mib-Sol♭-Ti-Reb-Fa', 'Ab', 'Abm11', 'Ab-C♭-Eb-G♭-B♭-D♭-F'),
('LAb', 'Lab Settima add11', 'Lab-Do-Mib-Sol-Ti-Fa', 'Ab', 'Ab7add11', 'Ab-C-Eb-G♭-B♭-D♭-F');

-- Creazione della tabella LAdiesis
CREATE TABLE NoteLAdiesis (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);
-- Inserimento dei dati per gli accordi di La# nella tabella LA#
INSERT INTO NoteLA# (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('LA#', 'La# Maggiore', 'La#-Do##-Mi#', 'A#', 'A#Maj', 'A#-D##-F#'),
('LA#', 'La# Minore', 'La#-Do#-Mi#', 'A#', 'A#m', 'A#-D#-F#'),
('LA#', 'La# Settima', 'La#-Do##-Mi#-Sol#', 'A#', 'A#7', 'A#-D##-F#-A#'),
('LA#', 'La# Maggiore 7', 'La#-Do##-Mi#-Sol##', 'A#', 'A#Maj7', 'A#-D##-F#-A##'),
('LA#', 'La# Minore 7', 'La#-Do#-Mi#-Sol#', 'A#', 'A#m7', 'A#-D#-F#-A#'),
('LA#', 'La# Settima Minore', 'La#-Do#-Mi#-Sol#', 'A#', 'A#m7', 'A#-D#-F#-A#'),
('LA#', 'La# Maggiore 6', 'La#-Do##-Mi#-Fa#', 'A#', 'A#6', 'A#-D##-F#-Bb'),
('LA#', 'La# Minore 6', 'La#-Do#-Mi#-Fa#', 'A#', 'A#m6', 'A#-D#-F#-Bb'),
('LA#', 'La# Settima 9', 'La#-Do##-Mi#-Sol#-Si#', 'A#', 'A#9', 'A#-D##-F#-A#-C#'),
('LA#', 'La# Maggiore 9', 'La#-Do##-Mi#-Sol##-Si#', 'A#', 'A#Maj9', 'A#-D##-F#-A##-C#'),
('LA#', 'La# Minore 9', 'La#-Do#-Mi#-Sol#-Si#', 'A#', 'A#m9', 'A#-D#-F#-A#-C#'),
('LA#', 'La# Settima Maggiore 7', 'La#-Do##-Mi#-Sol##-Si#', 'A#', 'A#Maj7♯5', 'A#-D##-F#-A##-C#'),
('LA#', 'La# Diminuito', 'La#-Do#-Mi♭-Sol#', 'A#', 'A#dim', 'A#-D#-F-#A'),
('LA#', 'La# Aumentato', 'La#-Do##-Mi#-Sol##', 'A#', 'A#aug', 'A#-D##-F##-A##'),
('LA#', 'La# Sesta', 'La#-Do##-Mi#-Fa#-Si#', 'A#', 'A#6', 'A#-D##-F#-Bb-C#'),
('LA#', 'La# Nona', 'La#-Do##-Mi#-Sol#-Si#-Re#', 'A#', 'A#9', 'A#-D##-F#-A#-C#-E#'),
('LA#', 'La# Settima Maggiore', 'La#-Do##-Mi#-Sol##-Si#-Re#', 'A#', 'A#Maj7', 'A#-D##-F#-A##-C#-E#'),
('LA#', 'La# Settima Maggiore 9', 'La#-Do##-Mi#-Sol##-Si#-Re#-Fa#', 'A#', 'A#Maj9', 'A#-D##-F#-A##-C#-E#-G#'),
('LA#', 'La# Settima 11', 'La#-Do##-Mi#-Sol##-Si#-Re#-Fa#-La#', 'A#', 'A#11', 'A#-D##-F#-A##-C#-E#-G#-B#'),
('LA#', 'La# Settima 13', 'La#-Do##-Mi#-Sol##-Si#-Re#-Fa#-La#-Do##', 'A#', 'A#13', 'A#-D##-F#-A##-C#-E#-G#-B#-D##'),
('LA#', 'La# Settima 9 Add11', 'La#-Do##-Mi#-Sol##-Si#-Re#-Fa#', 'A#', 'A#9add11', 'A#-D##-F#-A##-C#-E#-G#-B#'),
('LA#', 'La# Sesta 9', 'La#-Do##-Mi#-Fa#-Si#-Re#-La#', 'A#', 'A#6/9', 'A#-D##-F#-Bb-C#-E#-A#'),
('LA#', 'La# Sesta 11', 'La#-Do##-Mi#-Fa#-Si#-Re#-La#-Do##', 'A#', 'A#6/11', 'A#-D##-F#-Bb-C#-E#-A#-D##'),
('LA#', 'La# Settima Maggiore 11', 'La#-Do##-Mi#-Sol##-Re#-Fa#', 'A#', 'A#Maj7#11', 'A#-D##-F#-A##-E#-G#'),
('LA#', 'La# Minore 7 Add11', 'La#-Do#-Mi#-Sol-Bb', 'A#', 'A#m7add11', 'A#-D#-F#-A#-Bb'),
('LA#', 'La# Maggiore 7#11', 'La#-Do##-Mi#-Sol##-Re#-Fa##', 'A#', 'A#Maj7#11', 'A#-D##-F#-A##-E#-G##'),
('LA#', 'La# Minore/Maggiore 7', 'La#-Do#-Mi#-Sol-B', 'A#', 'A#m/Maj7', 'A#-D#-F#-A#-B'),
('LA#', 'La# Settima 9#11', 'La#-Do##-Mi#-Sol#-Si#-Re#-Fa##', 'A#', 'A#9#11', 'A#-D##-F#-A#-C#-E#-G##'),
('LA#', 'La# Settima Minore 9', 'La#-Do#-Mi#-Sol#-Si#-Re#', 'A#', 'A#m9', 'A#-D#-F#-A#-C#-E#'),
('LA#', 'La# Settima Maggiore 13', 'La#-Do##-Mi#-Sol#-Ti#-Re#-Fa##-La#', 'A#', 'A#Maj13', 'A#-D##-F#-A#-C#-E#-G##-B#'),
('LA#', 'La# Minore 11', 'La#-Do#-Mi#-Sol-Bb-Si-Re-Fa', 'A#', 'A#m11', 'A#-D#-F#-A#-Bb-C#-E#-G#'),
('LA#', 'La# Settima add11', 'La#-Do##-Mi#-Sol##-Re#-Fa#', 'A#', 'A#7add11', 'A#-D##-F#-A##-E#-G#-B#');

-- Creazione della tabella SI
CREATE TABLE NoteLA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);
-- Inserimento dei dati per gli accordi di Si nella tabella SI
INSERT INTO NoteSI (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('SI', 'Si Maggiore', 'Si-Re♯-Fa♯', 'B', 'BMaj', 'B-D♯-F♯'),
('SI', 'Si Minore', 'Si-Re-Fa♯', 'B', 'Bm', 'B-D-F♯'),
('SI', 'Si Settima', 'Si-Re♯-Fa♯-La', 'B', 'B7', 'B-D♯-F♯-A'),
('SI', 'Si Maggiore 7', 'Si-Re♯-Fa♯-La♯', 'B', 'BMaj7', 'B-D♯-F♯-A♯'),
('SI', 'Si Minore 7', 'Si-Re-Fa♯-La', 'B', 'Bm7', 'B-D-F♯-A'),
('SI', 'Si Settima Minore', 'Si-Re-Fa♯-La', 'B', 'Bm7', 'B-D-F♯-A'),
('SI', 'Si Maggiore 6', 'Si-Re♯-Fa♯-La♯-Do♯', 'B', 'B6', 'B-D♯-F♯-A♯-C♯'),
('SI', 'Si Minore 6', 'Si-Re-Fa♯-La-Do♯', 'B', 'Bm6', 'B-D-F♯-A-C♯'),
('SI', 'Si Settima 9', 'Si-Re♯-Fa♯-La-Do♯-Mi', 'B', 'B9', 'B-D♯-F♯-A-C♯-E'),
('SI', 'Si Maggiore 9', 'Si-Re♯-Fa♯-La♯-Do♯-Mi', 'B', 'BMaj9', 'B-D♯-F♯-A♯-C♯-E'),
('SI', 'Si Minore 9', 'Si-Re-Fa♯-La-Do♯-Mi', 'B', 'Bm9', 'B-D-F♯-A-C♯-E'),
('SI', 'Si Settima Maggiore 7', 'Si-Re♯-Fa♯-La♯-Do♯-Mi', 'B', 'BMaj7♯5', 'B-D♯-F♯-A♯-C♯-E'),
('SI', 'Si Diminuito', 'Si-Re-Fa-La', 'B', 'Bdim', 'B-D-F-A'),
('SI', 'Si Aumentato', 'Si-Re♯-Fa♯-La♯', 'B', 'Baug', 'B-D♯-F♯-A♯'),
('SI', 'Si Sesta', 'Si-Re♯-Fa♯-La♯-Do♯-Mi', 'B', 'B6', 'B-D♯-F♯-A♯-C♯-E'),
('SI', 'Si Nona', 'Si-Re♯-Fa♯-La-Do♯-Mi-Sol♯', 'B', 'B9', 'B-D♯-F♯-A-C♯-E-G♯'),
('SI', 'Si Settima Maggiore', 'Si-Re♯-Fa♯-La-Do♯-Mi-Sol♯', 'B', 'BMaj7', 'B-D♯-F♯-A-C♯-E-G♯'),
('SI', 'Si Settima Maggiore 9', 'Si-Re♯-Fa♯-La♯-Do♯-Mi-Sol♯-Si♯', 'B', 'BMaj9', 'B-D♯-F♯-A♯-C♯-E-G♯-B♯'),
('SI', 'Si Settima 11', 'Si-Re♯-Fa♯-La-Do♯-Mi-Sol♯-Si♯-Re♯', 'B', 'B11', 'B-D♯-F♯-A-C♯-E-G♯-B♯-D♯'),
('SI', 'Si Settima 13', 'Si-Re♯-Fa♯-La-Do♯-Mi-Sol♯-Si♯-Re♯-Fa♯', 'B', 'B13', 'B-D♯-F♯-A-C♯-E-G♯-B♯-D♯-F♯'),
('SI', 'Si Settima 9 Add11', 'Si-Re♯-Fa♯-La-Do♯-Mi-Sol♯-Si♯-Fa♯', 'B', 'B9add11', 'B-D♯-F♯-A-C♯-E-G♯-B♯-F♯'),
('SI', 'Si Sesta 9', 'Si-Re♯-Fa♯-La♯-Do♯-Mi-Sol♯-Si', 'B', 'B6/9', 'B-D♯-F♯-A♯-C♯-E-G♯-B'),
('SI', 'Si Sesta 11', 'Si-Re♯-Fa♯-La♯-Do♯-Mi-Sol♯-Si-Re♯', 'B', 'B6/11', 'B-D♯-F♯-A♯-C♯-E-G♯-B-D♯'),
('SI', 'Si Settima Maggiore 11', 'Si-Re♯-Fa♯-La-Do♯-Mi-Sol♯-Si-Re♯-Fa#', 'B', 'BMaj7#11', 'B-D♯-F♯-A-C♯-E-G♯-B-D♯-F#'),
('SI', 'Si Minore 7 Add11', 'Si-Re-Fa-La-Do♯-Mi-Sol♯-Si♯', 'B', 'Bm7add11', 'B-D-F♯-A-C♯-E-G♯-B♯'),
('SI', 'Si Maggiore 7#11', 'Si-Re♯-Fa♯-La♯-Do♯-Mi-Sol♯-Si♯-Fa#', 'B', 'BMaj7#11', 'B-D♯-F♯-A-C♯-E-G♯-B-D♯-F#'),
('SI', 'Si Minore/Maggiore 7', 'Si-Re-Fa-La-Do♯-Mi-Sol♯-Si', 'B', 'Bm/Maj7', 'B-D-F♯-A-C♯-E-G♯-B'),
('SI', 'Si Settima 9#11', 'Si-Re♯-Fa♯-La-Do♯-Mi-Sol♯-Si♯-Fa#', 'B', 'B9#11', 'B-D♯-F♯-A-C♯-E-G♯-B-D♯-F#'),
('SI', 'Si Settima Minore 9', 'Si-Re-Fa♯-La-Do♯-Mi♯-Sol♯-Si', 'B', 'Bm9', 'B-D-F♯-A-C♯-E♯-G♯-B'),
('SI', 'Si Settima Maggiore 13', 'Si-Re♯-Fa♯-La♯-Do♯-Mi-Sol♯-Si-Re♯-Fa#', 'B', 'BMaj13', 'B-D♯-F♯-A-C♯-E-G♯-B-D♯-F#'),
('SI', 'Si Minore 11', 'Si-Re-Fa-La-Do♯-Mi-Sol-Si-Re', 'B', 'Bm11', 'B-D-F♯-A-C♯-E-G-B-D♯'),
('SI', 'Si Settima add11', 'Si-Re♯-Fa♯-La♯-Do♯-Mi-Sol♯-Si♯-Fa#', 'B', 'B7add11', 'B-D♯-F♯-A-C♯-E-G♯-B-D♯-F#');

-- Creazione della tabella SIb
CREATE TABLE NoteLA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);
-- Inserimento dei dati per gli accordi di Si♭ nella tabella SIb
INSERT INTO NoteSIb (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('SI♭', 'Si♭ Maggiore', 'Si♭-Re-Fa', 'B♭', 'B♭Maj', 'B♭-D-F'),
('SI♭', 'Si♭ Minore', 'Si♭-Re♭-Fa', 'B♭', 'B♭m', 'B♭-D♭-F'),
('SI♭', 'Si♭ Settima', 'Si♭-Re-Fa-La♭', 'B♭', 'B♭7', 'B♭-D-F-A♭'),
('SI♭', 'Si♭ Maggiore 7', 'Si♭-Re-Fa-La', 'B♭', 'B♭Maj7', 'B♭-D-F-A'),
('SI♭', 'Si♭ Minore 7', 'Si♭-Re♭-Fa-La♭', 'B♭', 'B♭m7', 'B♭-D♭-F-A♭'),
('SI♭', 'Si♭ Settima Minore', 'Si♭-Re♭-Fa-La♭', 'B♭', 'B♭m7', 'B♭-D♭-F-A♭'),
('SI♭', 'Si♭ Maggiore 6', 'Si♭-Re-Fa-La-Do', 'B♭', 'B♭6', 'B♭-D-F-A-C'),
('SI♭', 'Si♭ Minore 6', 'Si♭-Re♭-Fa-La-Do', 'B♭', 'B♭m6', 'B♭-D♭-F-A-C'),
('SI♭', 'Si♭ Settima 9', 'Si♭-Re-Fa-La-Do-Mi', 'B♭', 'B♭9', 'B♭-D-F-A-C-E'),
('SI♭', 'Si♭ Maggiore 9', 'Si♭-Re-Fa-La-Do-Mi', 'B♭', 'B♭Maj9', 'B♭-D-F-A-C-E'),
('SI♭', 'Si♭ Minore 9', 'Si♭-Re♭-Fa-La-Do-Mi', 'B♭', 'B♭m9', 'B♭-D♭-F-A♭-C-E'),
('SI♭', 'Si♭ Settima Maggiore 7', 'Si♭-Re-Fa-La-Do-Mi', 'B♭', 'B♭Maj7♯5', 'B♭-D-F-A-C-E'),
('SI♭', 'Si♭ Diminuito', 'Si♭-Re♭-Fa♭-La♭', 'B♭', 'B♭dim', 'B♭-D♭-F♭-A♭'),
('SI♭', 'Si♭ Aumentato', 'Si♭-Re-Fa♯-La', 'B♭', 'B♭aug', 'B♭-D-F♯-A'),
('SI♭', 'Si♭ Sesta', 'Si♭-Re-Fa-La-Do-Sol', 'B♭', 'B♭6', 'B♭-D-F-A-C-G'),
('SI♭', 'Si♭ Nona', 'Si♭-Re-Fa-La-Do-Mi-Si', 'B♭', 'B♭9', 'B♭-D-F-A-C-E-B'),
('SI♭', 'Si♭ Settima Maggiore', 'Si♭-Re-Fa-La-Do-Mi-Si', 'B♭', 'B♭Maj7', 'B♭-D-F-A-C-E-B'),
('SI♭', 'Si♭ Settima Maggiore 9', 'Si♭-Re-Fa-La-Do-Mi-Si-Do♯', 'B♭', 'B♭Maj9', 'B♭-D-F-A-C-E-B-D♯'),
('SI♭', 'Si♭ Settima 11', 'Si♭-Re-Fa-La-Do-Sol-Si-Re', 'B♭', 'B♭11', 'B♭-D-F-A-C-G-B-D♯'),
('SI♭', 'Si♭ Settima 13', 'Si♭-Re-Fa-La-Do-Mi-Si-Do♯-Re♯-Fa', 'B♭', 'B♭13', 'B♭-D-F-A-C-E-B-D♯-F'),
('SI♭', 'Si♭ Settima 9 Add11', 'Si♭-Re-Fa-La-Do-Sol-Si-Fa', 'B♭', 'B♭9add11', 'B♭-D-F-A-C-G-B-F'),
('SI♭', 'Si♭ Sesta 9', 'Si♭-Re-Fa-La-Do-Sol-Si-Mi', 'B♭', 'B♭6/9', 'B♭-D-F-A-C-G-B-E'),
('SI♭', 'Si♭ Sesta 11', 'Si♭-Re-Fa-La-Do-Sol-Si-Mi-Re♯', 'B♭', 'B♭6/11', 'B♭-D-F-A-C-G-B-E-D♯'),
('SI♭', 'Si♭ Settima Maggiore 11', 'Si♭-Re-Fa-La-Do-Mi-Si-Do♯-Re♯-Fa#', 'B♭', 'B♭Maj7#11', 'B♭-D-F-A-C-E-B-D♯-F#'),
('SI♭', 'Si♭ Minore 7 Add11', 'Si♭-Re♭-Fa-La-Do-Sol-Si♭-Do♭', 'B♭', 'B♭m7add11', 'B♭-D♭-F-A♭-C-G♭-B♭'),
('SI♭', 'Si♭ Maggiore 7#11', 'Si♭-Re-Fa-La-Do-Mi-Si-Do♯-Re♯-Fa#', 'B♭', 'B♭Maj7#11', 'B♭-D-F-A-C-E-B-D♯-F#'),
('SI♭', 'Si♭ Minore/Maggiore 7', 'Si♭-Re♭-Fa-La-Do-Sol-Si♭-Do', 'B♭', 'B♭m/Maj7', 'B♭-D♭-F-A♭-C-G-B♭'),
('SI♭', 'Si♭ Settima 9#11', 'Si♭-Re-Fa-La-Do-Sol-Si♭-Do♭-Fa#', 'B♭', 'B♭9#11', 'B♭-D-F-A-C-G-B♭-D♭-F#'),
('SI♭', 'Si♭ Settima Minore 9', 'Si♭-Re♭-Fa♭-La♭-Do♭-Mi♭-Si♭', 'B♭', 'B♭m9', 'B♭-D♭-F♭-A♭-C♭-E♭-B♭'),
('SI♭', 'Si♭ Settima Maggiore 13', 'Si♭-Re-Fa-La-Do-Mi-Si-Do♯-Re♯-Fa#', 'B♭', 'B♭Maj13', 'B♭-D-F-A-C-E-B-D♯-F#'),
('SI♭', 'Si♭ Minore 11', 'Si♭-Re♭-Fa♭-La-Do♭-Mi♭-Si♭-Do', 'B♭', 'B♭m11', 'B♭-D♭-F♭-A-C♭-E♭-B♭-C'),
('SI♭', 'Si♭ Settima add11', 'Si♭-Re-Fa-La-Do-Sol-Si♭-Do♭-Fa', 'B♭', 'B♭7add11', 'B♭-D-F-A-C-G-B♭-D♭-F'),
('SI♭', 'Si♭ Sesta 9', 'Si♭-Re-Fa-La-Do-Sol-Si♭-Mi♭-Do♭', 'B♭', 'B♭6/9', 'B♭-D-F-A-C-G-B♭-E♭-C♭');

-- Creazione della tabella SIdiesis
CREATE TABLE NoteLA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    note_ita VARCHAR(255),
    chord_ita VARCHAR(255),
    chord_note_ita VARCHAR(255),
    note_eng VARCHAR(255),
    chord_eng VARCHAR(255),
    chord_note_eng VARCHAR(255)
);
-- Inserimento dei dati per gli accordi di Si# nella tabella SI#
INSERT INTO NoteSI# (note_ita, chord_ita, chord_note_ita, note_eng, chord_eng, chord_note_eng) VALUES
('SI#', 'Si# Maggiore', 'Si#-Re♯♯-Fa♯♯', 'B#', 'B#Maj', 'B#-Dx-Fx'),
('SI#', 'Si# Minore', 'Si#-Re♯-Fa♯♯', 'B#', 'B#m', 'B#-Dx-Fx'),
('SI#', 'Si# Settima', 'Si#-Re♯♯-Fa♯♯-La♯', 'B#', 'B#7', 'B#-Dx-Fx-Ax'),
('SI#', 'Si# Maggiore 7', 'Si#-Re♯♯-Fa♯♯-La♯♯', 'B#', 'B#Maj7', 'B#-Dx-Fx-Ax'),
('SI#', 'Si# Minore 7', 'Si#-Re♯-Fa♯♯-La♯', 'B#', 'B#m7', 'B#-Dx-Fx-Ax'),
('SI#', 'Si# Settima Minore', 'Si#-Re♯-Fa♯♯-La♯', 'B#', 'B#m7', 'B#-Dx-Fx-Ax'),
('SI#', 'Si# Maggiore 6', 'Si#-Re♯♯-Fa♯♯-La♯♯-Do♯♯', 'B#', 'B#6', 'B#-Dx-Fx-Ax-Cx'),
('SI#', 'Si# Minore 6', 'Si#-Re♯-Fa♯♯-La♯-Do♯♯', 'B#', 'B#m6', 'B#-Dx-Fx-Ax-Cx'),
('SI#', 'Si# Settima 9', 'Si#-Re♯♯-Fa♯♯-La♯-Do♯♯-Mi♯', 'B#', 'B#9', 'B#-Dx-Fx-Ax-Cx-Ex'),
('SI#', 'Si# Maggiore 9', 'Si#-Re♯♯-Fa♯♯-La♯♯-Do♯♯-Mi♯', 'B#', 'B#Maj9', 'B#-Dx-Fx-Ax-Cx-Ex'),
('SI#', 'Si# Minore 9', 'Si#-Re♯-Fa♯♯-La♯-Do♯♯-Mi♯', 'B#', 'B#m9', 'B#-Dx-Fx-Ax-Cx-Ex'),
('SI#', 'Si# Settima Maggiore 7', 'Si#-Re♯♯-Fa♯♯-La♯-Do♯♯-Mi♯', 'B#', 'B#Maj7♯5', 'B#-Dx-Fx-Ax-Cx-Ex'),
('SI#', 'Si# Diminuito', 'Si#-Re♯-Fa♯♯-La', 'B#', 'B#dim', 'B#-Dx-Fx-A'),
('SI#', 'Si# Aumentato', 'Si#-Re♯♯-Fa♯♯♯', 'B#', 'B#aug', 'B#-Dx-Fxx-Ax'),
('SI#', 'Si# Sesta', 'Si#-Re♯♯-Fa♯♯-La♯♯-Do♯♯-Mi♯', 'B#', 'B#6', 'B#-Dx-Fx-Ax-Cx-Ex'),
('SI#', 'Si# Nona', 'Si#-Re♯♯-Fa♯♯-La♯-Do♯♯-Mi♯-Sol♯♯', 'B#', 'B#9', 'B#-Dx-Fx-Ax-Cx-Ex-Gx'),
('SI#', 'Si# Settima Maggiore', 'Si#-Re♯♯-Fa♯♯-La♯-Do♯♯-Mi♯-Sol♯♯', 'B#', 'B#Maj7', 'B#-Dx-Fx-Ax-Cx-Ex-Gx'),
('SI#', 'Si# Settima Maggiore 9', 'Si#-Re♯♯-Fa♯♯-La♯♯-Do♯♯-Mi♯-Sol♯♯-Si♯♯', 'B#', 'B#Maj9', 'B#-Dx-Fx-Ax-Cx-Ex-Gx-Bx♯'),
('SI#', 'Si# Settima 11', 'Si#-Re♯♯-Fa♯♯♯-La♯-Do♯♯-Mi♯-Sol♯♯-Si♯-Re♯♯', 'B#', 'B#11', 'B#-Dx-Fxx-Ax-Cx-Ex-Gx-Bx♯-Dx♯'),
('SI#', 'Si# Settima 13', 'Si#-Re♯♯-Fa♯♯-La♯-Do♯♯-Mi♯-Sol♯♯-Si♯-Re♯♯-Fa♯', 'B#', 'B#13', 'B#-Dx-Fxx-Ax-Cx-Ex-Gx-Bx♯-Dx♯-Fx'),
('SI#', 'Si# Settima 9 Add11', 'Si#-Re♯♯-Fa♯♯-La♯-Do♯♯-Mi♯-Sol♯♯-Si♯-Re♯♯-Fa♯', 'B#', 'B#9add11', 'B#-Dx-Fxx-Ax-Cx-Ex-Gx-Bx♯-Dx♯-Fx'),
('SI#', 'Si# Sesta 9', 'Si#-Re♯♯-Fa♯♯-La♯♯-Do♯♯-Mi♯-Sol♯-Si♯-Re♯', 'B#', 'B#6/9', 'B#-Dx-Fx-Ax-Cx-Ex-Gx-Bx♯-E♯'),
('SI#', 'Si# Sesta 11', 'Si#-Re♯♯-Fa♯♯♯-La♯♯-Do♯♯-Mi♯-Sol♯-Si♯-Re♯-Fa♯', 'B#', 'B#6/11', 'B#-Dx-Fxx-Ax-Cx-Ex-Gx-Bx♯-E♯-Dx♯'),
('SI#', 'Si# Settima Maggiore 11', 'Si#-Re♯♯-Fa♯♯-La♯-Do♯♯-Mi♯-Sol♯-Si♯-Re♯-Fa♯♯♯', 'B#', 'B#Maj7#11', 'B#-Dx-Fxx-Ax-Cx-Ex-Gx-Bx♯-Dx♯-Fx-#x'),
('SI#', 'Si# Minore 7 Add11', 'Si#-Re♯-Fa♯♯-La-Do♯♯-Mi♯-Sol♯♯-Si♯', 'B#', 'B#m7add11', 'B#-Dx-Fx-Ax-Cx-Ex-Gx-Bx'),
('SI#', 'Si# Maggiore 7#11', 'Si#-Re♯♯-Fa♯♯-La♯-Do♯♯-Mi♯-Sol♯♯-Si♯-Re♯♯-Fa♯♯♯', 'B#', 'B#Maj7#11', 'B#-Dx-Fxx-Ax-Cx-Ex-Gx-Bx♯-Dx♯-Fx-#x'),
('SI#', 'Si# Minore/Maggiore 7', 'Si#-Re♯-Fa♯♯-La-Do♯♯-Mi♯-Sol♯♯-Si♯', 'B#', 'B#m/Maj7', 'B#-Dx-Fx-Ax-Cx-Ex-Gx-Bx'),
('SI#', 'Si# Settima 9#11', 'Si#-Re♯♯-Fa♯♯♯-La♯-Do♯♯-Mi♯-Sol♯-Si♯-Re♯♯-Fa♯', 'B#', 'B#9#11', 'B#-Dx-Fxx-Ax-Cx-Ex-Gx-Bx♯-Dx♯-Fx-#x'),
('SI#', 'Si# Settima Minore 9', 'Si#-Re♯-Fa♯-La-Do♯♯-Mi♯♯-Sol♯♯-Si♯', 'B#', 'B#m9', 'B#-Dx-Fx-Ax-Cx-Exx-Gx-Bx'),
('SI#', 'Si# Settima Maggiore 13', 'Si#-Re♯♯-Fa♯♯-La♯-Do♯♯-Mi♯-Sol♯-Si♯-Re♯♯-Fa♯-La♯', 'B#', 'B#Maj13', 'B#-Dx-Fxx-Ax-Cx-Ex-Gx-Bx♯-Dx♯-Fx-#x-Gx'),
('SI#', 'Si# Minore 11', 'Si#-Re♯-Fa♯♯♯-La-Do♯♯♯-Mi♯-Sol♯♯-Si♯-Re♯-Fa♯-La', 'B#', 'B#m11', 'B#-Dx-Fxx-Ax-Cx-Ex-Gx-Bx♯-Dx♯-Fx-#x-Gx'),
('SI#', 'Si# Settima add11', 'Si#-Re♯♯-Fa♯♯-La♯-Do♯♯-Mi♯-Sol♯♯-Si♯-Re♯♯-Fa♯-La', 'B#', 'B#7add11', 'B#-Dx-Fxx-Ax-Cx-Ex-Gx-Bx♯-Dx♯-Fx-#x-Gx');
